/**
 * 
 */
package com.HuskySoft.metrobike.backend;

/**
 * @author coreyh3
 *
 */
public class StubGoogleAPIWrapper implements APIQuery {

    /**
     * Dummy JSON bicycle directions.
     */
    private static final String DUMMY_BICYCLE_JSON = "{"
            + "\n   \"routes\" : [\n    "
            + "  {\n         \"bounds\" : {\n            \"northeast\" : {\n  "
            + "             \"lat\" : 47.676040,\n               \"lng\" : -12"
            + "2.313250\n            },\n            \"southwest\" : {\n      "
            + "         \"lat\" : 47.65358000000001,\n               \"lng\" :"
            + " -122.325820\n            }\n         },\n         \"copyrights"
            + "\" : \"Map data \u00a92013 Google\",\n         \"legs\" : [\n  "
            + "          {\n               \"distance\" : {\n                 "
            + " \"text\" : \"2.1 mi\",\n                  \"value\" : 3402\n  "
            + "             },\n               \"duration\" : {\n             "
            + "     \"text\" : \"13 mins\",\n                  \"value\" : 761"
            + "\n               },\n               \"end_address\" : \"3801 Br"
            + "ooklyn Avenue Northeast, University of Washington, Seattle, WA "
            + "98105, USA\",\n               \"end_location\" : {\n           "
            + "       \"lat\" : 47.65390000000001,\n                  \"lng\" "
            + ": -122.314480\n               },\n               \"start_addres"
            + "s\" : \"6504 Latona Avenue Northeast, Seattle, WA 98115, USA\","
            + "\n               \"start_location\" : {\n                  \"la"
            + "t\" : 47.676040,\n                  \"lng\" : -122.325820\n    "
            + "           },\n               \"steps\" : [\n                  "
            + "{\n                     \"distance\" : {\n                     "
            + "   \"text\" : \"59 ft\",\n                        \"value\" : 1"
            + "8\n                     },\n                     \"duration\" :"
            + " {\n                        \"text\" : \"1 min\",\n            "
            + "            \"value\" : 6\n                     },\n           "
            + "          \"end_location\" : {\n                        \"lat\""
            + " : 47.675910,\n                        \"lng\" : -122.325690\n "
            + "                    },\n                     \"html_instruction"
            + "s\" : \"Head \\u003cb\\u003esoutheast\\u003c/b\\u003e on \\u003"
            + "cb\\u003eLatona Ave NE\\u003c/b\\u003e toward \\u003cb\\u003eNE"
            + " 65th St\\u003c/b\\u003e\",\n                     \"polyline\" "
            + ": {\n                        \"points\" : \"gv~aHjwriVXY\"\n   "
            + "                  },\n                     \"start_location\" :"
            + " {\n                        \"lat\" : 47.676040,\n             "
            + "           \"lng\" : -122.325820\n                     },\n    "
            + "                 \"travel_mode\" : \"BICYCLING\"\n             "
            + "     },\n                  {\n                     \"distance\""
            + " : {\n                        \"text\" : \"0.2 mi\",\n         "
            + "               \"value\" : 252\n                     },\n      "
            + "               \"duration\" : {\n                        \"text"
            + "\" : \"1 min\",\n                        \"value\" : 63\n      "
            + "               },\n                     \"end_location\" : {\n "
            + "                       \"lat\" : 47.67588000000001,\n          "
            + "              \"lng\" : -122.322330\n                     },\n "
            + "                    \"html_instructions\" : \"Turn \\u003cb\\u0"
            + "03eleft\\u003c/b\\u003e onto \\u003cb\\u003eNE 65th St\\u003c/b"
            + "\\u003e\",\n                     \"polyline\" : {\n            "
            + "            \"points\" : \"mu~aHpvriV@s@@qE@gE?w@?u@?cB\"\n    "
            + "                 },\n                     \"start_location\" : "
            + "{\n                        \"lat\" : 47.675910,\n              "
            + "          \"lng\" : -122.325690\n                     },\n     "
            + "                \"travel_mode\" : \"BICYCLING\"\n              "
            + "    },\n                  {\n                     \"distance\" "
            + ": {\n                        \"text\" : \"0.4 mi\",\n          "
            + "              \"value\" : 593\n                     },\n       "
            + "              \"duration\" : {\n                        \"text"
            + "\" : \"2 mins\",\n                        \"value\" : 142\n    "
            + "                 },\n                     \"end_location\" : {"
            + "\n                        \"lat\" : 47.67201000000001,\n       "
            + "                 \"lng\" : -122.317360\n                     },"
            + "\n                     \"html_instructions\" : \"Turn \\u003cb"
            + "\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eNE Ravenna Blv"
            + "d\\u003c/b\\u003e\",\n                     \"polyline\" : {\n  "
            + "                      \"points\" : \"gu~aHpariVZYn@m@bA{@x@s@PO"
            + "FI`@]XWBCBEZYNOh@e@dB{ALMPOjC}BZYN]Jq@|@}G\"\n                 "
            + "    },\n                     \"start_location\" : {\n          "
            + "              \"lat\" : 47.67588000000001,\n                   "
            + "     \"lng\" : -122.322330\n                     },\n          "
            + "           \"travel_mode\" : \"BICYCLING\"\n                  }"
            + ",\n                  {\n                     \"distance\" : {\n"
            + "                        \"text\" : \"1.1 mi\",\n               "
            + "         \"value\" : 1775\n                     },\n           "
            + "          \"duration\" : {\n                        \"text\" : "
            + "\"6 mins\",\n                        \"value\" : 378\n         "
            + "            },\n                     \"end_location\" : {\n    "
            + "                    \"lat\" : 47.65609000000001,\n             "
            + "           \"lng\" : -122.317880\n                     },\n    "
            + "                 \"html_instructions\" : \"Turn \\u003cb\\u003e"
            + "right\\u003c/b\\u003e onto \\u003cb\\u003eRoosevelt Way NE\\u00"
            + "3c/b\\u003e\",\n                     \"polyline\" : {\n        "
            + "                \"points\" : \"a}}aHnbqiVnA?X?nC?jC?V?f@?|@?VAp"
            + "C@fA@~E@~B?hA@P?r@?xB@b@?^?`A@R?jCAjB@~GDj@F^PRLHDHBFBJ@L?tC?~@"
            + "BpA@r@@`DBlD@|BB\\\\?^@r@?L@@?PDHB\"\n                     },\n"
            + "                     \"start_location\" : {\n                  "
            + "      \"lat\" : 47.67201000000001,\n                        \"l"
            + "ng\" : -122.317360\n                     },\n                  "
            + "   \"travel_mode\" : \"BICYCLING\"\n                  },\n     "
            + "             {\n                     \"distance\" : {\n        "
            + "                \"text\" : \"0.2 mi\",\n                       "
            + " \"value\" : 348\n                     },\n                    "
            + " \"duration\" : {\n                        \"text\" : \"2 mins"
            + "\",\n                        \"value\" : 114\n                 "
            + "    },\n                     \"end_location\" : {\n            "
            + "            \"lat\" : 47.65598000000001,\n                     "
            + "   \"lng\" : -122.313250\n                     },\n            "
            + "         \"html_instructions\" : \"Turn \\u003cb\\u003eleft\\u0"
            + "03c/b\\u003e onto \\u003cb\\u003eNE Campus Pkwy\\u003c/b\\u003e"
            + "\",\n                     \"polyline\" : {\n                   "
            + "     \"points\" : \"qyzaHveqiVDS@I@IAkAByB?OBkE@sB?C?qB@wB@qB\""
            + "\n                     },\n                     \"start_locatio"
            + "n\" : {\n                        \"lat\" : 47.65609000000001,\n"
            + "                        \"lng\" : -122.317880\n                "
            + "     },\n                     \"travel_mode\" : \"BICYCLING\"\n"
            + "                  },\n                  {\n                    "
            + " \"distance\" : {\n                        \"text\" : \"0.2 mi"
            + "\",\n                        \"value\" : 268\n                 "
            + "    },\n                     \"duration\" : {\n                "
            + "        \"text\" : \"1 min\",\n                        \"value"
            + "\" : 31\n                     },\n                     \"end_lo"
            + "cation\" : {\n                        \"lat\" : 47.653580000000"
            + "01,\n                        \"lng\" : -122.313340\n           "
            + "          },\n                     \"html_instructions\" : \"Tu"
            + "rn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eUni"
            + "versity Way NE\\u003c/b\\u003e\",\n                     \"polyl"
            + "ine\" : {\n                        \"points\" : \"{xzaHxhpiV^B|"
            + "A@hCDlB@L@zA@\"\n                     },\n                     "
            + "\"start_location\" : {\n                        \"lat\" : 47.65"
            + "598000000001,\n                        \"lng\" : -122.313250\n "
            + "                    },\n                     \"travel_mode\" : "
            + "\"BICYCLING\"\n                  },\n                  {\n     "
            + "                \"distance\" : {\n                        \"tex"
            + "t\" : \"371 ft\",\n                        \"value\" : 113\n   "
            + "                  },\n                     \"duration\" : {\n  "
            + "                      \"text\" : \"1 min\",\n                  "
            + "      \"value\" : 21\n                     },\n                "
            + "     \"end_location\" : {\n                        \"lat\" : 47"
            + ".654220,\n                        \"lng\" : -122.314470\n      "
            + "               },\n                     \"html_instructions\" :"
            + " \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u00"
            + "3eBurke-Gilman Trail\\u003c/b\\u003e\",\n                     "
            + "\"polyline\" : {\n                        \"points\" : \"{izaHj"
            + "ipiVM`@Sh@EHCDEBIDGDEDINEJOb@Un@\"\n                     },\n  "
            + "                   \"start_location\" : {\n                    "
            + "    \"lat\" : 47.65358000000001,\n                        \"lng"
            + "\" : -122.313340\n                     },\n                    "
            + " \"travel_mode\" : \"BICYCLING\"\n                  },\n       "
            + "           {\n                     \"distance\" : {\n          "
            + "              \"text\" : \"115 ft\",\n                        "
            + "\"value\" : 35\n                     },\n                     "
            + "\"duration\" : {\n                        \"text\" : \"1 min\","
            + "\n                        \"value\" : 6\n                     }"
            + ",\n                     \"end_location\" : {\n                 "
            + "       \"lat\" : 47.65390000000001,\n                        \""
            + "lng\" : -122.314480\n                     },\n                 "
            + "    \"html_instructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b"
            + "\\u003e onto \\u003cb\\u003eBrooklyn Ave NE\\u003c/b\\u003e\\u0"
            + "03cdiv style=\\\"font-size:0.9em\\\"\\u003eDestination will be "
            + "on the right\\u003c/div\\u003e\",\n                     \"polyl"
            + "ine\" : {\n                        \"points\" : \"{mzaHlppiVp@@"
            + "L?\"\n                     },\n                     \"start_loc"
            + "ation\" : {\n                        \"lat\" : 47.654220,\n    "
            + "                    \"lng\" : -122.314470\n                    "
            + " },\n                     \"travel_mode\" : \"BICYCLING\"\n    "
            + "              }\n               ],\n               \"via_waypoi"
            + "nt\" : []\n            }\n         ],\n         \"overview_poly"
            + "line\" : {\n            \"points\" : \"gv~aHjwriVXY@s@ByK?mB?cB"
            + "ZYrBiBjAcAfAcAxAuApGwFZYN]hAoIdK?tCAxPDbLDvF?~GDj@Fr@^RHRDbD?fJ"
            + "JhJF`A@RDHBDSBS@eEB{EBaJ@qB^BfFFzBBzA@M`@Yr@IHQJOTUn@Un@p@@L?\""
            + "\n         },\n         \"summary\" : \"Roosevelt Way NE\",\n  "
            + "       \"warnings\" : [\n            \"Bicycling directions are"
            + " in beta. Use caution \u2013 This route may contain streets tha"
            + "t aren\'t suited for bicycling.\"\n         ],\n         \"wayp"
            + "oint_order\" : []\n      }\n   ],\n   \"status\" : \"OK\"\n}";
    
    
    /* (non-Javadoc)
     * @see com.HuskySoft.metrobike.backend.APIQuery#doQuery(java.lang.String)
     */
    @Override
    public String doQuery(String theURL) {
       
        return DUMMY_BICYCLE_JSON;
    }

}
