/**
 * 
 */
package com.HuskySoft.metrobike.backend;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * @author coreyh3
 * 
 *         This class is the stub class that returns JSON strings based on the
 *         query string.
 * 
 */
public class StubGoogleAPIWrapper implements APIQuery {

    /**
     * TAG for logging statements.
     */
    private static final String TAG = "com.HuskySoft.metrobike.backend: StubGoogleAPIWrapper.java: ";

    /**
     * HashMap for holding the query to JSON response mappings enabling us to
     * simulate the Google APIs without actually connecting to them.
     */
    private final Map<String, String> queryMap = new HashMap<String, String>();

    /**
     * This is a valid query that returns a valid JSON result.
     */
    private final String case1URLQuery = "http://maps.googleapis.com/maps/api/directions/json?"
            + "origin=302+NE+50th+St%2CSeattle%2CWA&destination=3801+Brooklyn+Ave+NE%"
            + "2CSeattle%2CWA&sensor=true&mode=bicycling&alternatives=true&language=en";

    /**
     * This is the JSON response that the case1URLQuery maps to.
     */
    private final String case1JSONResponseStandardResponse = "{\"routes\" : [ {\"bounds\" : { \"northeast\" : {\"lat\" : 47"
            + ".664990,\"lng\" : -122.314470 }, \"southwest\" : {\"lat\" : 47"
            + ".65390000000001,\"lng\" : -122.326230 }},\"copyrights\" : \"Ma"
            + "p data \u00a92013 Google\",\"legs\" : [ {\"distance\" : { \"te"
            + "xt\" : \"1.4 mi\", \"value\" : 2199},\"duration\" : { \"text\""
            + " : \"9 mins\", \"value\" : 527},\"end_address\" : \"3801 Brook"
            + "lyn Avenue Northeast, University of Washington, Seattle, WA 981"
            + "05, USA\",\"end_location\" : { \"lat\" : 47.65390000000001, \"l"
            + "ng\" : -122.314480},\"start_address\" : \"302 Northeast 50th St"
            + "reet, Seattle, WA 98105, USA\",\"start_location\" : { \"lat\" :"
            + " 47.664990, \"lng\" : -122.32540},\"steps\" : [ {\"distance\" :"
            + " { \"text\" : \"177 ft\", \"value\" : 54},\"duration\" : { \"te"
            + "xt\" : \"1 min\", \"value\" : 13},\"end_location\" : { \"lat\" "
            + ": 47.664990, \"lng\" : -122.326130},\"html_instructions\" : \""
            + "Head \\u003cb\\u003ewest\\u003c/b\\u003e on \\u003cb\\u003eNE "
            + "50th St\\u003c/b\\u003e toward \\u003cb\\u003eLatona Ave NE"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"eq|aHvtri"
            + "V?h@?fB\"},\"start_location\" : { \"lat\" : 47.664990, \"lng\""
            + " : -122.32540},\"travel_mode\" : \"BICYCLING\" }, {\"distance\""
            + " : { \"text\" : \"0.5 mi\", \"value\" : 811},\"duration\" : { "
            + "\"text\" : \"3 mins\", \"value\" : 195},\"end_location\" : { "
            + "\"lat\" : 47.65770000000001, \"lng\" : -122.326230},\"html_instructi"
            + "ons\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u00"
            + "3eThackeray Pl NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"e"
            + "q|aHhyriVjJBdIDb@?`FB|F@zFB\"},\"start_location\" : { \"lat\" : 47.66"
            + "4990, \"lng\" : -122.326130},\"travel_mode\" : \"BICYCLING\" }, {\"di"
            + "stance\" : { \"text\" : \"141 ft\", \"value\" : 43},\"duration\" : { "
            + "\"text\" : \"1 min\", \"value\" : 5},\"end_location\" : { \"lat\" : 4"
            + "7.65770000000001, \"lng\" : -122.325660},\"html_instructions\" : \"Tu"
            + "rn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003eNE 42nd St"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"sc{aH|yriV?qB\"},\""
            + "start_location\" : { \"lat\" : 47.65770000000001, \"lng\" : -122.326"
            + "230},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" :"
            + " \"0.1 mi\", \"value\" : 227},\"duration\" : { \"text\" : \"1 min\","
            + " \"value\" : 32},\"end_location\" : { \"lat\" : 47.655650, \"lng\" :"
            + " -122.325670},\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u"
            + "003c/b\\u003e onto \\u003cb\\u003eLatona Ave NE\\u003c/b\\u003e\",\""
            + "polyline\" : { \"points\" : \"sc{aHjvriVxK@\"},\"start_location\" : "
            + "{ \"lat\" : 47.65770000000001, \"lng\" : -122.325660},\"travel_mode\""
            + " : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"112 ft\", \"value"
            + "\" : 34},\"duration\" : { \"text\" : \"1 min\", \"value\" : 32},\"en"
            + "d_location\" : { \"lat\" : 47.65557000000001, \"lng\" : -122.326110}"
            + ",\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e"
            + " onto \\u003cb\\u003eNE 40th St\\u003c/b\\u003e\",\"polyline\" : { "
            + "\"points\" : \"yvzaHlvriVNvA\"},\"start_location\" : { \"lat\" : 47"
            + ".655650, \"lng\" : -122.325670},\"travel_mode\" : \"BICYCLING\" }, "
            + "{\"distance\" : { \"text\" : \"108 ft\", \"value\" : 33},\"duration"
            + "\" : { \"text\" : \"1 min\", \"value\" : 24},\"end_location\" : { "
            + "\"lat\" : 47.655520, \"lng\" : -122.325690},\"html_instructions\" : "
            + "\"Sharp \\u003cb\\u003eleft\\u003c/b\\u003e to stay on \\u003cb\\u00"
            + "3eNE 40th St\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"ivzaH"
            + "dyriVDe@BU?W\"},\"start_location\" : { \"lat\" : 47.65557000000001, "
            + "\"lng\" : -122.326110},\"travel_mode\" : \"BICYCLING\" }, {\"distanc"
            + "e\" : { \"text\" : \"266 ft\", \"value\" : 81},\"duration\" : { \"te"
            + "xt\" : \"1 min\", \"value\" : 44},\"end_location\" : { \"lat\" : 47."
            + "65479000000001, \"lng\" : -122.32570},\"html_instructions\" : \"Turn"
            + " \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eLatona Ave"
            + " NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"_vzaHpvriVbC@L"
            + "?\"},\"start_location\" : { \"lat\" : 47.655520, \"lng\" : -122.3256"
            + "90},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : "
            + "\"0.5 mi\", \"value\" : 881},\"duration\" : { \"text\" : \"3 mins\","
            + " \"value\" : 177},\"end_location\" : { \"lat\" : 47.654220, \"lng\" "
            + ": -122.314470},\"html_instructions\" : \"Turn \\u003cb\\u003eleft\\u"
            + "003c/b\\u003e onto \\u003cb\\u003eBurke-Gilman Trail\\u003c/b\\u003e"
            + "\",\"polyline\" : { \"points\" : \"mqzaHrvriV?WAS?IMaAMgAGe@CSUsBUqB"
            + "WiBCO?CAE?A?CAC?CCS?ACQ?AAM?A?A?AAA?A?AAIAG?IIi@CYEm@CWASCs@AU@i@@o@"
            + "?SB_@@YBWDe@Hk@h@sDHi@Fa@PsAf@oDFe@TwABORy@BGD[DU@M@ODc@De@@I@KDOBOZ"
            + "eABO\"},\"start_location\" : { \"lat\" : 47.65479000000001, \"lng\" "
            + ": -122.32570},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \""
            + "text\" : \"115 ft\", \"value\" : 35},\"duration\" : { \"text\" : \"1"
            + " min\", \"value\" : 5},\"end_location\" : { \"lat\" : 47.65390000000"
            + "001, \"lng\" : -122.314480},\"html_instructions\" : \"Turn \\u003cb"
            + "\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eBrooklyn Ave NE\\u0"
            + "03c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eDestinati"
            + "on will be on the right\\u003c/div\\u003e\",\"polyline\" : { \"point"
            + "s\" : \"{mzaHlppiVp@@L?\"},\"start_location\" : { \"lat\" : 47.65422"
            + "0, \"lng\" : -122.314470},\"travel_mode\" : \"BICYCLING\" }],\"via_w"
            + "aypoint\" : [] }],\"overview_polyline\" : { \"points\" : \"eq|aHvtri"
            + "V?pCpTH~VH?qBxK@NvADe@Bm@pC@Ak@MkAo@uFu@_GI_AOmAOsBEiAByAHeBNqAr@}Eh"
            + "AkIXgBVaANoAN_BH_@^uA~@@\"},\"summary\" : \"Thackeray Pl NE and Burk"
            + "e-Gilman Trail\",\"warnings\" : [ \"Bicycling directions are in beta"
            + ". Use caution \u2013 This route may contain streets that aren\'t sui"
            + "ted for bicycling.\"],\"waypoint_order\" : [] }, {\"bounds\" : { \"n"
            + "ortheast\" : {\"lat\" : 47.664990,\"lng\" : -122.313250 }, \"southwe"
            + "st\" : {\"lat\" : 47.65358000000001,\"lng\" : -122.32540 }},\"copyri"
            + "ghts\" : \"Map data \u00a92013 Google\",\"legs\" : [ {\"distance\" :"
            + " { \"text\" : \"1.5 mi\", \"value\" : 2352},\"duration\" : { \"text\""
            + " : \"9 mins\", \"value\" : 514},\"end_address\" : \"3801 Brooklyn Ave"
            + "nue Northeast, University of Washington, Seattle, WA 98105, USA\",\"e"
            + "nd_location\" : { \"lat\" : 47.65390000000001, \"lng\" : -122.314480}"
            + ",\"start_address\" : \"302 Northeast 50th Street, Seattle, WA 98105, "
            + "USA\",\"start_location\" : { \"lat\" : 47.664990, \"lng\" : -122.3254"
            + "0},\"steps\" : [ {\"distance\" : { \"text\" : \"0.4 mi\", \"value\" :"
            + " 599},\"duration\" : { \"text\" : \"3 mins\", \"value\" : 169},\"end_"
            + "location\" : { \"lat\" : 47.664950, \"lng\" : -122.31740},\"html_inst"
            + "ructions\" : \"Head \\u003cb\\u003eeast\\u003c/b\\u003e on \\u003cb\\"
            + "u003eNE 50th St\\u003c/b\\u003e toward \\u003cb\\u003eLatona Ave NE"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"eq|aHvtriV@gA?sE?"
            + "aF@iA?C?]?E?g@?K@o@?C?C?mA?_A@aAAcC@eB?yE?I?eE\"},\"start_location\" :"
            + " { \"lat\" : 47.664990, \"lng\" : -122.32540},\"travel_mode\" : \"BICY"
            + "CLING\" }, {\"distance\" : { \"text\" : \"0.6 mi\", \"value\" : 989},"
            + "\"duration\" : { \"text\" : \"3 mins\", \"value\" : 173},\"end_locati"
            + "on\" : { \"lat\" : 47.65609000000001, \"lng\" : -122.317880},\"html_i"
            + "nstructions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u0"
            + "03cb\\u003eRoosevelt Way NE\\u003c/b\\u003e\",\"polyline\" : { \"poin"
            + "ts\" : \"}p|aHvbqiV^?`A@R?jCAjB@~GDj@F^PRLHDHBFBJ@L?tC?~@BpA@r@@`DBlD"
            + "@|BB\\\\?^@r@?L@@?PDHB\"},\"start_location\" : { \"lat\" : 47.664950,"
            + " \"lng\" : -122.31740},\"travel_mode\" : \"BICYCLING\" }, {\"distance"
            + "\" : { \"text\" : \"0.2 mi\", \"value\" : 348},\"duration\" : { \"tex"
            + "t\" : \"2 mins\", \"value\" : 114},\"end_location\" : { \"lat\" : 47."
            + "65598000000001, \"lng\" : -122.313250},\"html_instructions\" : \"Turn"
            + " \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003eNE Campus Pk"
            + "wy\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"qyzaHveqiVDS@I@I"
            + "AkAByB?OBkE@sB?C?qB@wB@qB\"},\"start_location\" : { \"lat\" : 47.6560"
            + "9000000001, \"lng\" : -122.317880},\"travel_mode\" : \"BICYCLING\" },"
            + " {\"distance\" : { \"text\" : \"0.2 mi\", \"value\" : 268},\"duration"
            + "\" : { \"text\" : \"1 min\", \"value\" : 31},\"end_location\" : { \"l"
            + "at\" : 47.65358000000001, \"lng\" : -122.313340},\"html_instructions\""
            + " : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eU"
            + "niversity Way NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"{"
            + "xzaHxhpiV^B|A@hCDlB@L@zA@\"},\"start_location\" : { \"lat\" : 47.655"
            + "98000000001, \"lng\" : -122.313250},\"travel_mode\" : \"BICYCLING\" "
            + "}, {\"distance\" : { \"text\" : \"371 ft\", \"value\" : 113},\"durat"
            + "ion\" : { \"text\" : \"1 min\", \"value\" : 21},\"end_location\" : {"
            + " \"lat\" : 47.654220, \"lng\" : -122.314470},\"html_instructions\" :"
            + " \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eBur"
            + "ke-Gilman Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"{i"
            + "zaHjipiVM`@Sh@EHCDEBIDGDEDINEJOb@Un@\"},\"start_location\" : { \"lat"
            + "\" : 47.65358000000001, \"lng\" : -122.313340},\"travel_mode\" : \"B"
            + "ICYCLING\" }, {\"distance\" : { \"text\" : \"115 ft\", \"value\" : 3"
            + "5},\"duration\" : { \"text\" : \"1 min\", \"value\" : 6},\"end_locat"
            + "ion\" : { \"lat\" : 47.65390000000001, \"lng\" : -122.314480},\"html"
            + "_instructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\"
            + "u003cb\\u003eBrooklyn Ave NE\\u003c/b\\u003e\\u003cdiv style=\\\"fon"
            + "t-size:0.9em\\\"\\u003eDestination will be on the right\\u003c/div\\"
            + "u003e\",\"polyline\" : { \"points\" : \"{mzaHlppiVp@@L?\"},\"start_l"
            + "ocation\" : { \"lat\" : 47.654220, \"lng\" : -122.314470},\"travel_m"
            + "ode\" : \"BICYCLING\" }],\"via_waypoint\" : [ {\"location\" : { \"la"
            + "t\" : 47.65600280, \"lng\" : -122.3147020},\"step_index\" : 2,\"step"
            + "_interpolation\" : 0.6879778168404895 }] }],\"overview_polyline\" : "
            + "{ \"points\" : \"eq|aHvtriVBwS@cA?sI@oO`G?jKFj@F^P\\\\RPFX@tEBtMHnFD"
            + "j@JF]?uAHiMB_J|BDvFFhBBa@jAINOHMJOZe@rA~@@\"},\"summary\" : \"NE 50t"
            + "h St and Roosevelt Way NE\",\"warnings\" : [ \"Bicycling directions "
            + "are in beta. Use caution \u2013 This route may contain streets that "
            + "aren\'t suited for bicycling.\"],\"waypoint_order\" : [] }, {\"bound"
            + "s\" : { \"northeast\" : {\"lat\" : 47.664990,\"lng\" : -122.313170 }"
            + ", \"southwest\" : {\"lat\" : 47.65358000000001,\"lng\" : -122.32540 "
            + "}},\"copyrights\" : \"Map data \u00a92013 Google\",\"legs\" : [ {\"d"
            + "istance\" : { \"text\" : \"1.5 mi\", \"value\" : 2351},\"duration\" "
            + ": { \"text\" : \"10 mins\", \"value\" : 574},\"end_address\" : \"380"
            + "1 Brooklyn Avenue Northeast, University of Washington, Seattle, WA 9"
            + "8105, USA\",\"end_location\" : { \"lat\" : 47.65390000000001, \"lng\""
            + " : -122.314480},\"start_address\" : \"302 Northeast 50th Street, Sea"
            + "ttle, WA 98105, USA\",\"start_location\" : { \"lat\" : 47.664990, \""
            + "lng\" : -122.32540},\"steps\" : [ {\"distance\" : { \"text\" : \"0.4"
            + " mi\", \"value\" : 599},\"duration\" : { \"text\" : \"3 mins\", \"va"
            + "lue\" : 169},\"end_location\" : { \"lat\" : 47.664950, \"lng\" : -12"
            + "2.31740},\"html_instructions\" : \"Head \\u003cb\\u003eeast\\u003c/b"
            + "\\u003e on \\u003cb\\u003eNE 50th St\\u003c/b\\u003e toward \\u003cb"
            + "\\u003eLatona Ave NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" :"
            + " \"eq|aHvtriV@gA?sE?aF@iA?C?]?E?g@?K@o@?C?C?mA?_A@aAAcC@eB?yE?I?eE\""
            + "},\"start_location\" : { \"lat\" : 47.664990, \"lng\" : -122.32540},"
            + "\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0."
            + "4 mi\", \"value\" : 569},\"duration\" : { \"text\" : \"2 mins\", \"v"
            + "alue\" : 122},\"end_location\" : { \"lat\" : 47.659860, \"lng\" : -1"
            + "22.317740},\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u003"
            + "c/b\\u003e onto \\u003cb\\u003eRoosevelt Way NE\\u003c/b\\u003e\",\""
            + "polyline\" : { \"points\" : \"}p|aHvbqiV^?`A@R?jCAjB@~GDj@F^PRLHDHBF"
            + "BJ@L?tC?~@B\"},\"start_location\" : { \"lat\" : 47.664950, \"lng\" :"
            + " -122.31740},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \""
            + "text\" : \"0.2 mi\", \"value\" : 343},\"duration\" : { \"text\" : \""
            + "3 mins\", \"value\" : 174},\"end_location\" : { \"lat\" : 47.65980, "
            + "\"lng\" : -122.313170},\"html_instructions\" : \"Turn \\u003cb\\u003"
            + "eleft\\u003c/b\\u003e onto \\u003cb\\u003eNE 43rd St\\u003c/b\\u003e"
            + "\",\"polyline\" : { \"points\" : \"cq{aHzdqiV@sB?mB@mB?A@a@?qA@oB?A?"
            + "sBBuB?oB\"},\"start_location\" : { \"lat\" : 47.659860, \"lng\" : -1"
            + "22.317740},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"te"
            + "xt\" : \"0.4 mi\", \"value\" : 692},\"duration\" : { \"text\" : \"1 "
            + "min\", \"value\" : 82},\"end_location\" : { \"lat\" : 47.65358000000"
            + "001, \"lng\" : -122.313340},\"html_instructions\" : \"Turn \\u003cb\\"
            + "u003eright\\u003c/b\\u003e onto \\u003cb\\u003eUniversity Way NE\\u0"
            + "03c/b\\u003e\",\"polyline\" : { \"points\" : \"wp{aHhhpiVfC@~CBfED"
            + "\\\\?bAB|B@T?TA^B|A@hCDlB@L@zA@\"},\"start_location\" : { \"lat\" : "
            + "47.65980, \"lng\" : -122.313170},\"travel_mode\" : \"BICYCLING\" }, "
            + "{\"distance\" : { \"text\" : \"371 ft\", \"value\" : 113},\"duration"
            + "\" : { \"text\" : \"1 min\", \"value\" : 21},\"end_location\" : { \""
            + "lat\" : 47.654220, \"lng\" : -122.314470},\"html_instructions\" : \""
            + "Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eBurke-"
            + "Gilman Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"{izaH"
            + "jipiVM`@Sh@EHCDEBIDGDEDINEJOb@Un@\"},\"start_location\" : { \"lat\" "
            + ": 47.65358000000001, \"lng\" : -122.313340},\"travel_mode\" : \"BICY"
            + "CLING\" }, {\"distance\" : { \"text\" : \"115 ft\", \"value\" : 35},"
            + "\"duration\" : { \"text\" : \"1 min\", \"value\" : 6},\"end_location"
            + "\" : { \"lat\" : 47.65390000000001, \"lng\" : -122.314480},\"html_in"
            + "structions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u00"
            + "3cb\\u003eBrooklyn Ave NE\\u003c/b\\u003e\\u003cdiv style=\\\"font-s"
            + "ize:0.9em\\\"\\u003eDestination will be on the right\\u003c/div\\u00"
            + "3e\",\"polyline\" : { \"points\" : \"{mzaHlppiVp@@L?\"},\"start_loca"
            + "tion\" : { \"lat\" : 47.654220, \"lng\" : -122.314470},\"travel_mode"
            + "\" : \"BICYCLING\" }],\"via_waypoint\" : [ {\"location\" : { \"lat\""
            + " : 47.6598260, \"lng\" : -122.31519280},\"step_index\" : 2,\"step_in"
            + "terpolation\" : 0.5574277502663384 }] }],\"overview_polyline\" : { \""
            + "points\" : \"eq|aHvtriVBwS@cA?sI@oO`G?jKFj@F^P\\\\RPFX@tEBBqIBeFBiF?"
            + "oBfC@fJH`BBrC@t@@bJJzA@M`@Yr@IHQJOTUn@Un@p@@L?\"},\"summary\" : \"N"
            + "E 50th St and University Way NE\",\"warnings\" : [ \"Bicycling dire"
            + "ctions are in beta. Use caution \u2013 This route may contain stree"
            + "ts that aren\'t suited for bicycling.\"],\"waypoint_order\" : [] }]"
            + ",\"status\" : \"OK\" }";

    /**
     * This is a valid query that returns a really big JSON response. Note that
     * Java has a size limit of 2^16 for the number of chars in a String
     * variable declared at compile time.
     */
    private final String case2URLQuery = "http://maps.googleapis.com/maps/api/directions/json?"
            + "origin=302+NE+50th+St%2CSeattle%2CWA&destination=Everett&sensor=true"
            + "&mode=bicycling&alternatives=true&language=en";

    /**
     * The JSON response that the case2URLQuery maps to.
     */
    private final String case2JSONResponseStressTest = "{\"routes\" : [ {\"bounds\" : { \"northeast\" : {\"lat\" "
            + ": 47.979240,\"lng\" : -122.200410 }, \"southwest\" : {\""
            + "lat\" : 47.664990,\"lng\" : -122.352790 }},\"copyrights\" "
            + ": \"Map data \u00a92013 Google\",\"legs\" : [ {\"distance\""
            + " : { \"text\" : \"29.4 mi\", \"value\" : 47259},\"duration\" "
            + ": { \"text\" : \"2 hours 45 mins\", \"value\" : 9920},\"end"
            + "_address\" : \"Everett, WA, USA\",\"end_location\" : { \"lat\""
            + " : 47.97922000000001, \"lng\" : -122.202080},\"start_address\" "
            + ": \"302 Northeast 50th Street, Seattle, WA 98105, USA\",\"start_"
            + "location\" : { \"lat\" : 47.664990, \"lng\" : -122.32540},\"steps"
            + "\" : [ {\"distance\" : { \"text\" : \"52 ft\", \"value\" : 16},\""
            + "duration\" : { \"text\" : \"1 min\", \"value\" : 6},\"end_locatio"
            + "n\" : { \"lat\" : 47.664990, \"lng\" : -122.325610},\"html_instru"
            + "ctions\" : \"Head \\u003cb\\u003ewest\\u003c/b\\u003e on \\u003"
            + "cb\\u003eNE 50th St\\u003c/b\\u003e toward \\u003cb\\u003eLatona"
            + " Ave NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"eq|"
            + "aHvtriV?h@\"},\"start_location\" : { \"lat\" : 47.664990, \""
            + "lng\" : -122.32540},\"travel_mode\" : \"BICYCLING\" }, {\""
            + "distance\" : { \"text\" : \"0.8 mi\", \"value\" : 1214},\"d"
            + "uration\" : { \"text\" : \"3 mins\", \"value\" : 187},\"end"
            + "_location\" : { \"lat\" : 47.67590000000001, \"lng\" : -122"
            + ".325430},\"html_instructions\" : \"Turn \\u003cb\\u003erig"
            + "ht\\u003c/b\\u003e onto \\u003cb\\u003eLatona Ave NE\\u003"
            + "c/b\\u003e\",\"polyline\" : { \"points\" : \"eq|aH`vriVqC?"
            + "oCAqCAqCEqC?qC?sCCsCAoCCmC?MAKAwAAmAAkA@mACiA?mAAkAAwCA\"},\""
            + "start_location\" : { \"lat\" : 47.664990, \"lng\" : -122.325610},"
            + "\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : "
            + "\"66 ft\", \"value\" : 20},\"duration\" : { \"text\" : \"1 min\", "
            + "\"value\" : 25},\"end_location\" : { \"lat\" : 47.675910, \"lng\" "
            + ": -122.325690},\"html_instructions\" : \"Turn \\u003cb\\u003"
            + "eleft\\u003c/b\\u003e onto \\u003cb\\u003eNE 65th St\\u003c"
            + "/b\\u003e\",\"polyline\" : { \"points\" : \"ku~aH|triVAr@\""
            + "},\"start_location\" : { \"lat\" : 47.67590000000001, \"lng"
            + "\" : -122.325430},\"travel_mode\" : \"BICYCLING\" }, {\"dis"
            + "tance\" : { \"text\" : \"0.1 mi\", \"value\" : 218},\"durat"
            + "ion\" : { \"text\" : \"1 min\", \"value\" : 26},\"end_locat"
            + "ion\" : { \"lat\" : 47.677570, \"lng\" : -122.327230},\"ht"
            + "ml_instructions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003"
            + "e onto \\u003cb\\u003eLatona Ave NE\\u003c/b\\u003e\",\"poly"
            + "line\" : { \"points\" : \"mu~aHpvriVwFbF}@|@UP\"},\"start_l"
            + "ocation\" : { \"lat\" : 47.675910, \"lng\" : -122.3256"
            + "90},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \""
            + "text\" : \"299 ft\", \"value\" : 91},\"duration\" : { \"tex"
            + "t\" : \"1 min\", \"value\" : 11},\"end_location\" : { \"la"
            + "t\" : 47.678370, \"lng\" : -122.327510},\"html_instructio"
            + "ns\" : \"Continue onto \\u003cb\\u003e2nd Ave NE\\u003c/b"
            + "\\u003e\",\"polyline\" : { \"points\" : \"y__bHd`siVkAVsA"
            + "^\"},\"start_location\" : { \"lat\" : 47.677570, \"lng\" :"
            + " -122.327230},\"travel_mode\" : \"BICYCLING\" }, {\"distan"
            + "ce\" : { \"text\" : \"0.9 mi\", \"value\" : 1453},\"durati"
            + "on\" : { \"text\" : \"5 mins\", \"value\" : 301},\"end_lo"
            + "cation\" : { \"lat\" : 47.68562000000001, \"lng\" : -122.3"
            + "37990},\"html_instructions\" : \"Turn \\u003cb\\u003eright"
            + "\\u003c/b\\u003e onto \\u003cb\\u003eEast Green Lake Way N"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"yd_bH|a"
            + "siVGg@G_@Ia@CMEOQc@GOKQGMEGIKMQ[YUSQMOGg@UUKKESDM?_@BE@"
            + "QD[JWNOJk@`@[^W\\\\[l@GNi@bAs@pA{ArCGJINMZKXKXIZGXI^EZI"
            + "l@E^ANARARAXAj@@d@?N@J?JBd@Bf@Df@?T@T?X?Z?TC`@AVAPE^E`@"
            + "EZERELQp@a@fAKPGJGJOTKLWVs@t@gChCKH}B~BMNGDKLIJEDCDEHGJ"
            + "CFIXENOn@EVE^APAJAH?LAL?J@j@@f@@N@LBP\"},\"start_locati"
            + "on\" : { \"lat\" : 47.678370, \"lng\" : -122.327510},\"t"
            + "ravel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"te"
            + "xt\" : \"328 ft\", \"value\" : 100},\"duration\" : { \"t"
            + "ext\" : \"1 min\", \"value\" : 20},\"end_location\" : { "
            + "\"lat\" : 47.685130, \"lng\" : -122.339090},\"html_ins"
            + "tructions\" : \"Continue onto \\u003cb\\u003eWest Green "
            + "Lake Dr N\\u003c/b\\u003e\",\"polyline\" : { \"points\" "
            + ": \"cr`bHlcuiVBRDRFRHZRl@d@~@JT\"},\"start_location\" : "
            + "{ \"lat\" : 47.68562000000001, \"lng\" : -122.337990},\""
            + "travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"te"
            + "xt\" : \"217 ft\", \"value\" : 66},\"duration\" : { \""
            + "text\" : \"1 min\", \"value\" : 18},\"end_location\" : "
            + "{ \"lat\" : 47.684780, \"lng\" : -122.339810},\"html_i"
            + "nstructions\" : \"Continue onto \\u003cb\\u003eWinona "
            + "Ave N\\u003c/b\\u003e\",\"polyline\" : { \"points\" :"
            + " \"ao`bHhjuiVLXv@tB\"},\"start_location\" : { \"lat\" "
            + ": 47.685130, \"lng\" : -122.339090},\"travel_mode\" : "
            + "\"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.6 mi"
            + "\", \"value\" : 942},\"duration\" : { \"text\" : \"6 m"
            + "ins\", \"value\" : 337},\"end_location\" : { \"lat\" : "
            + "47.684760, \"lng\" : -122.352390},\"html_instructions\""
            + " : \"Slight \\u003cb\\u003eright\\u003c/b\\u003e onto "
            + "\\u003cb\\u003eN 77th St\\u003c/b\\u003e\",\"polyline\""
            + " : { \"points\" : \"{l`bHxnuiV?hK?~K?jB?`@@lO@vO?tN\"},"
            + "\"start_location\" : { \"lat\" : 47.684780, \"lng\" : -"
            + "122.339810},\"travel_mode\" : \"BICYCLING\" }, {\"dist"
            + "ance\" : { \"text\" : \"1.7 mi\", \"value\" : 2664},\"d"
            + "uration\" : { \"text\" : \"11 mins\", \"value\" : 689},"
            + "\"end_location\" : { \"lat\" : 47.708710, \"lng\" : "
            + "-122.352790},\"html_instructions\" : \"Turn \\u003cb"
            + "\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eDay"
            + "ton Ave N\\u003c/b\\u003e\",\"polyline\" : { \"points"
            + "\" : \"wl`bHl}wiVkA?gA?gAHgAHiAFgAHqC?e@?wAAO?oC?sC?u"
            + "CDQ?O?wD?qC@gJ?iJFiJBiJBiJBoC?gA@kA?cA@iA?gA@iA@gA?gA"
            + "?yE@oC@_C@gE@U?M?\"},\"start_location\" : { \"lat\" "
            + ": 47.684760, \"lng\" : -122.352390},\"travel_mode\" "
            + ": \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0."
            + "1 mi\", \"value\" : 234},\"duration\" : { \"text\" : "
            + "\"1 min\", \"value\" : 38},\"end_location\" : { \"lat\""
            + " : 47.708690, \"lng\" : -122.349660},\"html_instructions\""
            + " : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto "
            + "\\u003cb\\u003eN 110th St\\u003c/b\\u003e\",\"polyline"
            + "\" : { \"points\" : \"mbebH|_xiV@iGAgC?cC@aA@Y\"},\""
            + "start_location\" : { \"lat\" : 47.708710, \"lng\" : "
            + "-122.352790},\"travel_mode\" : \"BICYCLING\" }, {\"dis"
            + "tance\" : { \"text\" : \"0.9 mi\", \"value\" : 1491},\""
            + "duration\" : { \"text\" : \"5 mins\", \"value\" : 286}"
            + ",\"end_location\" : { \"lat\" : 47.72188000000001, \"l"
            + "ng\" : -122.348320},\"html_instructions\" : \"Turn "
            + "\\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003e"
            + "Interurban Trail\\u003c/b\\u003e\",\"polyline\" : { "
            + "\"points\" : \"ibebHjlwiVq@OqUwGc@KWGUEQCSAGAK?Q?a@@"
            + "W@K@G@IDYLGBG?I@I@G?SIEAG?C?Q?kAHuCPoAHqBL{F\\\\aBLC@"
            + "MDMHGBA?E@C@C?G@I@M@E?Q@E?Y@E?I@E?]A_@Ae@CK@GAaAGOAQ"
            + "CGAEAQIGGMGA?CACAC?qDYgAKSA\"},\"start_location\" : "
            + "{ \"lat\" : 47.708690, \"lng\" : -122.349660},\"trave"
            + "l_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\""
            + " : \"164 ft\", \"value\" : 50},\"duration\" : { \"tex"
            + "t\" : \"1 min\", \"value\" : 13},\"end_location\" : "
            + "{ \"lat\" : 47.72231000000001, \"lng\" : -122.34845"
            + "0},\"html_instructions\" : \"Slight \\u003cb\\u003el"
            + "eft\\u003c/b\\u003e to stay on \\u003cb\\u003eInteru"
            + "rban Trail\\u003c/b\\u003e\",\"polyline\" : { \"point"
            + "s\" : \"wtgbH~cwiVKDc@RC@C?C@YC\"},\"start_loca"
            + "tion\" : { \"lat\" : 47.72188000000001, \"lng\""
            + " : -122.348320},\"travel_mode\" : \"BICYCLING\""
            + " }, {\"distance\" : { \"text\" : \"43 ft\", \"va"
            + "lue\" : 13},\"duration\" : { \"text\" : \"1 min\""
            + ", \"value\" : 3},\"end_location\" : { \"lat\" : "
            + "47.722320, \"lng\" : -122.348280},\"html_instruc"
            + "tions\" : \"Turn \\u003cb\\u003eright\\u003c/b"
            + "\\u003e onto \\u003cb\\u003eN 128th St\\u003c/"
            + "b\\u003e\",\"polyline\" : { \"points\" : \"mwg"
            + "bHxdwiVAa@\"},\"start_location\" : { \"lat\" : "
            + "47.72231000000001, \"lng\" : -122.348450},\"tr"
            + "avel_mode\" : \"BICYCLING\" }, {\"distance\" : "
            + "{ \"text\" : \"0.7 mi\", \"value\" : 1114},\"du"
            + "ration\" : { \"text\" : \"4 mins\", \"value\" : "
            + "256},\"end_location\" : { \"lat\" : 47.732310000"
            + "00001, \"lng\" : -122.347750},\"html_instructio"
            + "ns\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e"
            + " onto \\u003cb\\u003eLinden Ave N\\u003c/b"
            + "\\u003e\",\"polyline\" : { \"points\" : \"o"
            + "wgbHvcwiVOCUCUAOA{@Eo@E[Ck@Cq@EcAIsAK_BQuAOY"
            + "Cs@E{@G]CqAA[?cD@cCBu@@yD?O?s@Aq@?kDBsC@iB?\"},\"s"
            + "tart_location\" : { \"lat\" : 47.722320, \"lng\" : -122"
            + ".348280},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : "
            + "{ \"text\" : \"10 ft\", \"value\" : 3},\"duration\" : { "
            + "\"text\" : \"1 min\", \"value\" : 1},\"end_location\" : "
            + "{ \"lat\" : 47.73231000000001, \"lng\" : -122.347710},\""
            + "html_instructions\" : \"Turn \\u003cb\\u003eright\\u003"
            + "c/b\\u003e onto \\u003cb\\u003eN 143rd St\\u003c/b\\u003e"
            + "\",\"polyline\" : { \"points\" : \"}uibHl`wiV?G\"},\"star"
            + "t_location\" : { \"lat\" : 47.73231000000001, \"lng\" : -1"
            + "22.347750},\"travel_mode\" : \"BICYCLING\" }, {\"distance"
            + "\" : { \"text\" : \"0.1 mi\", \"value\" : 202},\"duration"
            + "\" : { \"text\" : \"1 min\", \"value\" : 32},\"end_locati"
            + "on\" : { \"lat\" : 47.734130, \"lng\" : -122.347750},\"ht"
            + "ml_instructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b"
            + "\\u003e onto \\u003cb\\u003eLinden Ave N\\u003c/b\\u003e\""
            + ",\"polyline\" : { \"points\" : \"}uibHd`wiV[?W?oEBgBB\"},\""
            + "start_location\" : { \"lat\" : 47.73231000000001, \"lng\" :"
            + " -122.347710},\"travel_mode\" : \"BICYCLING\" }, {\"distan"
            + "ce\" : { \"text\" : \"36 ft\", \"value\" : 11},\"duration"
            + "\" : { \"text\" : \"1 min\", \"value\" : 34},\"end_location\" "
            + ": { \"lat\" : 47.734130, \"lng\" : -122.347890},\"html_instru"
            + "ctions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto "
            + "\\u003cb\\u003eN 145th St\\u003c/b\\u003e\",\"polyline\" : {"
            + " \"points\" : \"iajbHl`wiV?Z\"},\"start_location\" : { \"lat"
            + "\" : 47.734130, \"lng\" : -122.347750},\"travel_mode\" : \"B"
            + "ICYCLING\" }, {\"distance\" : { \"text\" : \"0.4 mi\", \"va"
            + "lue\" : 715},\"duration\" : { \"text\" : \"2 mins\", \"value"
            + "\" : 98},\"end_location\" : { \"lat\" : 47.740410, \"lng\" :"
            + " -122.345940},\"html_instructions\" : \"Turn \\u003cb\\u003"
            + "eright\\u003c/b\\u003e onto \\u003cb\\u003eInterurban Trail"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"iajbHha"
            + "wiV]AMGIEIGIGQKwAGyDw@yCs@SEwDw@iCm@gASqCm@eAWm@Km@OMC\"},\"sta"
            + "rt_location\" : { \"lat\" : 47.734130, \"lng\" : -122.347890"
            + "},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"tex"
            + "t\" : \"1.5 mi\", \"value\" : 2460},\"duration\" : { \"te"
            + "xt\" : \"9 mins\", \"value\" : 535},\"end_location\" : { \"l"
            + "at\" : 47.76081000000001, \"lng\" : -122.345550},\"html_instr"
            + "uctions\" : \"Slight \\u003cb\\u003eright\\u003c/b\\u003e to s"
            + "tay on \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"pol"
            + "yline\" : { \"points\" : \"qhkbHbuviVYM_@Si@YMGKGKEEAE?CAE?G@E"
            + "@CBC@CBMBQ?M?KAK?]BiADMDG?iAFiAQOA[BE@C@UBU@C@A@A@@B@@TTj@\\\\"
            + "@?BA@CACAAYi@I[AG?KAKCY?AAUASAMAEECMEc@G{@GUEg@Sg@Yi@Mu@Eg@Ck@"
            + "K_@@W@_@@aAGaACmE@aB?a@AUOSQQEY?sBA{FA{BAuGCs@@g@FYLa@Ae@BOBa@Ne@P"
            + "]?o@CYGYC_BAOEICGAO?K?SFe@?c@AMBYFUDoAZa@LsAZKBEDQN]\\\\MFa@J"
            + "E@eDx@yBh@y@Nu@DqD?KCCGEK?KAEKA\"},\"start_location\" : { \"la"
            + "t\" : 47.740410, \"lng\" : -122.345940},\"travel_mode\" : \"BI"
            + "CYCLING\" }, {\"distance\" : { \"text\" : \"0.2 mi\", \"valu"
            + "e\" : 270},\"duration\" : { \"text\" : \"1 min\", \"value\" : "
            + "46},\"end_location\" : { \"lat\" : 47.76307000000001, \"lng\""
            + " : -122.34560},\"html_instructions\" : \"Turn \\u003cb\\u003e"
            + "left\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban Tr"
            + "ail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"ahobHt"
            + "rviVKAC@ABAFAPCFEDG?SEUQOOOISA{@AUAS?KBOFYL[Hi@?iAAGEIE\"},"
            + "\"start_location\" : { \"lat\" : 47.76081000000001, \"lng\""
            + " : -122.345550},\"travel_mode\" : \"BICYCLING\" }, {\"dist"
            + "ance\" : { \"text\" : \"354 ft\", \"value\" : 108},\"durati"
            + "on\" : { \"text\" : \"1 min\", \"value\" : 21},\"end_location\" :"
            + " { \"lat\" : 47.763150, \"lng\" : -122.344180},\"html_instructio"
            + "ns\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e to stay on "
            + "\\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" "
            + ": { \"points\" : \"evobH~rviVGQAKEiB?sC\"},\"start_location\" "
            + ": { \"lat\" : 47.76307000000001, \"lng\" : -122.34560},\"trave"
            + "l_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.3"
            + " mi\", \"value\" : 459},\"duration\" : { \"text\" : \"2 mins\""
            + ", \"value\" : 90},\"end_location\" : { \"lat\" : 47.767240, \""
            + "lng\" : -122.344140},\"html_instructions\" : \"Turn \\u003cb"
            + "\\u003eleft\\u003c/b\\u003e to stay on \\u003cb\\u003eInterur"
            + "ban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"u"
            + "vobHbjviVQ?O?CICIw@@k@?u@AW@UDuABqC@uDBe@EY?}@?U?M?\"},\"star"
            + "t_location\" : { \"lat\" : 47.763150, \"lng\" : -122.344180},"
            + "\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\""
            + " : \"0.5 mi\", \"value\" : 827},\"duration\" : { \"text\" : "
            + "\"2 mins\", \"value\" : 135},\"end_location\" : { \"lat\" : "
            + "47.774180, \"lng\" : -122.340820},\"html_instructions\" : \""
            + "Slight \\u003cb\\u003eright\\u003c/b\\u003e to stay on \\u003"
            + "cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { "
            + "\"points\" : \"gppbHziviVK?KAKGIMI[M_@GCIGWAOCKEQOk@i@i@_@{A"
            + "{@eAi@g@Sk@S_@MOKMMWO[I]CSCKG{@_@_Bg@cBc@]OOIKIQIgCw@eAY_@C_@"
            + "?oA@g@C\"},\"start_location\" : { \"lat\" : 47.767240, \"lng"
            + "\" : -122.344140},\"travel_mode\" : \"BICYCLING\" }, {\"dist"
            + "ance\" : { \"text\" : \"0.3 mi\", \"value\" : 415},\"duration"
            + "\" : { \"text\" : \"2 mins\", \"value\" : 144},\"end_location"
            + "\" : { \"lat\" : 47.774190, \"lng\" : -122.335260},\"html_in"
            + "structions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e "
            + "onto \\u003cb\\u003eN 200th St/Interurban Trail\\u003c/b\\u003"
            + "e\",\"polyline\" : { \"points\" : \"s{qbHbuuiV?e@?{O?eF?yBA_A?uB"
            + "\"},\"start_location\" : { \"lat\" : 47.774180, \"lng\" : -122."
            + "340820},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \""
            + "text\" : \"0.2 mi\", \"value\" : 399},\"duration\" : { \"text\""
            + " : \"1 min\", \"value\" : 76},\"end_location\" : { \"lat\" : "
            + "47.77778000000001, \"lng\" : -122.335320},\"html_instructions\""
            + " : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb"
            + "\\u003eMeridian Ave N\\u003c/b\\u003e\",\"polyline\" : { \""
            + "points\" : \"u{qbHjrtiVY@iIBuIDS?\"},\"start_location\" : { "
            + "\"lat\" : 47.774190, \"lng\" : -122.335260},\"travel_mode\" "
            + ": \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.3 mi\", "
            + "\"value\" : 541},\"duration\" : { \"text\" : \"3 mins\", \"va"
            + "lue\" : 162},\"end_location\" : { \"lat\" : 47.782640, \"lng"
            + "\" : -122.335380},\"html_instructions\" : \"Continue onto "
            + "\\u003cb\\u003e76th Ave W/Interurban Trail\\u003c/b\\u003e\""
            + ",\"polyline\" : { \"points\" : \"crrbHvrtiVqD@qDBk@AsD@wA@uD"
            + "?yBB\"},\"start_location\" : { \"lat\" : 47.77778000000001, "
            + "\"lng\" : -122.335320},\"travel_mode\" : \"BICYCLING\" }, {"
            + "\"distance\" : { \"text\" : \"1.2 mi\", \"value\" : 1899},"
            + "\"duration\" : { \"text\" : \"6 mins\", \"value\" : 356},"
            + "\"end_location\" : { \"lat\" : 47.79870, \"lng\" : -122.3"
            + "29980},\"html_instructions\" : \"Turn \\u003cb\\u003eright"
            + "\\u003c/b\\u003e onto \\u003cb\\u003eInterurban Trail"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"opsbHbs"
            + "tiV?OAGAEEGGIGGEGEMMWO[y@wAU[cAeAg@g@W@cBa@_ACyAAcJQqEIgEs@"
            + "sBo@sAm@aDsAaCoA}@[{@_@EECEKAMAGACCCGI]CKCIAE?CA?KEk@Wg@UC?CA"
            + "G?C?E?EAEAKGEAE?C@G@G@KBI@EAUIkBu@o@Y]Q_@OsAOeAEa@Ng@H}A@m@AYA_@MOCMC"
            + "]CY?o@A_A@u@@Q?UBg@FG?EAEA\"},\"start_location\" : { \"lat\" : 47.78"
            + "2640, \"lng\" : -122.335380},\"travel_mode\" : \"BICYCLING\" }, {\""
            + "distance\" : { \"text\" : \"0.4 mi\", \"value\" : 652},\"duration\" : { "
            + "\"text\" : \"2 mins\", \"value\" : 114},\"end_location\" : { \"lat\" : "
            + "47.803190, \"lng\" : -122.325850},\"html_instructions\" : \"Slight "
            + "\\u003cb\\u003eleft\\u003c/b\\u003e to stay on \\u003cb\\u003eInteru"
            + "rban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"{tvbHj"
            + "qsiVa@Da@CaAIo@@i@?mAEc@MICM@WESIe@Se@Sc@Wc@[c@_@_@c@c@k@_AyAm@mAu@"
            + "gCa@{AUaACMAGAK?s@?Q?E?CCAG?\"},\"start_location\" : { \"lat\" : 47"
            + ".79870, \"lng\" : -122.329980},\"travel_mode\" : \"BICYCLING\" }, {"
            + "\"distance\" : { \"text\" : \"0.5 mi\", \"value\" : 764},\"duratio"
            + "n\" : { \"text\" : \"3 mins\", \"value\" : 167},\"end_location\" :"
            + " { \"lat\" : 47.80670000000001, \"lng\" : -122.317280},\"html_instr"
            + "uctions\" : \"Slight \\u003cb\\u003eleft\\u003c/b\\u003e to stay o"
            + "n \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : "
            + "{ \"points\" : \"}pwbHpwriVYECAAAACAEo@_C[kAK_@q@iCeA{Dc@eBe@eBGYk@"
            + "gBIc@Ie@U_Ae@_Bo@cCs@aCUo@MSIO]mAm@}BEOECQD\"},\"start_location\" : {"
            + " \"lat\" : 47.803190, \"lng\" : -122.325850},\"travel_mode\" : \"B"
            + "ICYCLING\" }, {\"distance\" : { \"text\" : \"466 ft\", \"value\" : 142"
            + "},\"duration\" : { \"text\" : \"1 min\", \"value\" : 60},\"end_locati"
            + "on\" : { \"lat\" : 47.80771000000001, \"lng\" : -122.317780},\"html_ins"
            + "tructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e to stay on "
            + "\\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { "
            + "\"points\" : \"{fxbH~aqiVEBE@AD?L?v@GLqB@aA@\"},\"start_location\" : "
            + "{ \"lat\" : 47.80670000000001, \"lng\" : -122.317280},\"travel_mode\" "
            + ": \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.2 mi\", \"value\" "
            + ": 247},\"duration\" : { \"text\" : \"1 min\", \"value\" : 44},\"end_lo"
            + "cation\" : { \"lat\" : 47.808350, \"lng\" : -122.31530},\"html_instruct"
            + "ions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb"
            + "\\u003e211th St SW/Interurban Trail\\u003c/b\\u003e\\u003cdiv style="
            + "\\\"font-size:0.9em\\\"\\u003eContinue to follow Interurban Trail"
            + "\\u003c/div\\u003e\",\"polyline\" : { \"points\" : \"emxbHbeqiVFwKM{@Q"
            + "OWMmA@A?\"},\"start_location\" : { \"lat\" : 47.80771000000001, \"lng"
            + "\" : -122.317780},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { "
            + "\"text\" : \"0.5 mi\", \"value\" : 786},\"duration\" : { \"text\" : \""
            + "3 mins\", \"value\" : 153},\"end_location\" : { \"lat\" : 47.809940, "
            + "\"lng\" : -122.305950},\"html_instructions\" : \"Turn \\u003cb\\u003e"
            + "right\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban Trail\\u003c/"
            + "b\\u003e\",\"polyline\" : { \"points\" : \"eqxbHrupiVEuA?GBYFUTc@j@e"
            + "@TQHGLOHQCScAoDm@gCOi@g@eCa@cCCQ_@yBO{@u@}EIc@w@_Fs@oECMIq@\"},\"start"
            + "_location\" : { \"lat\" : 47.808350, \"lng\" : -122.31530},\"travel_mo"
            + "de\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"89 ft\", \"val"
            + "ue\" : 27},\"duration\" : { \"text\" : \"1 min\", \"value\" : 5},\"end_l"
            + "ocation\" : { \"lat\" : 47.810180, \"lng\" : -122.305990},\"html_inst"
            + "ructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e to stay on "
            + "\\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { "
            + "\"points\" : \"c{xbHd{niV[@IDI?\"},\"start_location\" : { \"lat\" : 47."
            + "809940, \"lng\" : -122.305950},\"travel_mode\" : \"BICYCLING\" }, {"
            + "\"distance\" : { \"text\" : \"49 ft\", \"value\" : 15},\"duration\" : "
            + "{ \"text\" : \"1 min\", \"value\" : 29},\"end_location\" : { \"lat\" : 4"
            + "7.81026000000001, \"lng\" : -122.30590},\"html_instructions\" : \"Sligh"
            + "t \\u003cb\\u003eright\\u003c/b\\u003e to stay on \\u003cb\\u003eInter"
            + "urban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"s|xbHl{ni"
            + "VQA@O\"},\"start_location\" : { \"lat\" : 47.810180, \"lng\" : -122.305"
            + "990},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : "
            + "\"0.2 mi\", \"value\" : 282},\"duration\" : { \"text\" : \"1 min\", "
            + "\"value\" : 75},\"end_location\" : { \"lat\" : 47.810850, \"lng\" : "
            + "-122.303010},\"html_instructions\" : \"Slight \\u003cb\\u003eright"
            + "\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban Trail\\u003c/b"
            + "\\u003e\",\"polyline\" : { \"points\" : \"c}xbHzzniV@gGB{EC]Aa@AO?G?"
            + "C?A?ACAg@@gA@\"},\"start_location\" : { \"lat\" : 47.81026000000001, "
            + "\"lng\" : -122.30590},\"travel_mode\" : \"BICYCLING\" }, {\"distance"
            + "\" : { \"text\" : \"0.6 mi\", \"value\" : 950},\"duration\" : { \"te"
            + "xt\" : \"3 mins\", \"value\" : 164},\"end_location\" : { \"lat\" : 47"
            + ".81552000000001, \"lng\" : -122.293170},\"html_instructions\" : "
            + "\"Turn \\u003cb\\u003eright\\u003c/b\\u003e to stay on \\u003cb\\u003e"
            + "Interurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : "
            + "\"y`ybHxhniVm@aCyCmM}BaKScASkA_@}AqAsFy@mDG[AAACYiAIWCIGECAGCMAU?"
            + "E?CAEEg@c@qAiA}@u@CAC?oAC\"},\"start_location\" : { \"lat\" : 47.8"
            + "10850, \"lng\" : -122.303010},\"travel_mode\" : \"BICYCLING\" }, "
            + "{\"distance\" : { \"text\" : \"161 ft\", \"value\" : 49},\"durati"
            + "on\" : { \"text\" : \"1 min\", \"value\" : 16},\"end_location\" : "
            + "{ \"lat\" : 47.81550000000001, \"lng\" : -122.292630},\"html_instr"
            + "uctions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e to stay o"
            + "n \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" "
            + ": { \"points\" : \"_~ybHhkliVGOCGCEAI?IAG@G@I@GFKDIBA\"},\"start_l"
            + "ocation\" : { \"lat\" : 47.81552000000001, \"lng\" : -122.293170},"
            + "\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : "
            + "\"1.8 mi\", \"value\" : 2864},\"duration\" : { \"text\" : \"10 m"
            + "ins\", \"value\" : 587},\"end_location\" : { \"lat\" : 47.83095"
            + "000000001, \"lng\" : -122.26520},\"html_instructions\" : \"Turn "
            + "\\u003cb\\u003eright\\u003c/b\\u003e to stay on \\u003cb\\u003e"
            + "Interurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : "
            + "\"{}ybH|gliVF?D@D@FBDDDHHPBDB@D@FADEBGBIF[?AJy@BOBK?A@K?A@G@K@G?K?"
            + "IES[y@EGkAiCaBoDk@qA_A_CiAqCS[_@m@S_@Qa@We@IKEAE?Qe@]s@O[g@kA_@_"
            + "Ac@eAWm@GUESCSCIEMIQIMMMU_@OSM[o@uAm@kA_@s@CGAA{@cB?Ag@aAk@mA}"
            + "@}BOe@Oa@Uo@CGGSAA?AAEA??CACeAmCCGYu@qAwCQc@q@qBu@uBkBeEgBcEkA"
            + "oCoAuCyCaHaCqFeAeCO_@eB{DYq@AAWo@s@aBw@aB_@s@o@gAg@m@k@i@k@a@y@m@"
            + "YOUCWAKEoBwAKKIKQa@a@u@[_@]YIEIAGAEDYh@\"},\"start_location\" : "
            + "{ \"lat\" : 47.81550000000001, \"lng\" : -122.292630},\"travel_m"
            + "ode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.1 mi\","
            + " \"value\" : 171},\"duration\" : { \"text\" : \"1 min\", \"value"
            + "\" : 51},\"end_location\" : { \"lat\" : 47.832290, \"lng\" : -122."
            + "26450},\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u003c"
            + "/b\\u003e onto \\u003cb\\u003eBeech Rd/Interurban Trail\\u003c/"
            + "b\\u003e\",\"polyline\" : { \"points\" : \"m~|bHn|fiVW[}@aAQWIK"
            + "WQ[I_@Gc@?a@X\"},\"start_location\" : { \"lat\" : 47.830950000"
            + "00001, \"lng\" : -122.26520},\"travel_mode\" : \"BICYCLING\" },"
            + " {\"distance\" : { \"text\" : \"0.3 mi\", \"value\" : 418},\""
            + "duration\" : { \"text\" : \"2 mins\", \"value\" : 103},\"end_l"
            + "ocation\" : { \"lat\" : 47.834870, \"lng\" : -122.268440},\"htm"
            + "l_instructions\" : \"Slight \\u003cb\\u003eright\\u003c/b\\u003e"
            + " onto \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyl"
            + "ine\" : { \"points\" : \"yf}bHbxfiVGAI?E@KDUPQL[b@y@xA{AjCo@rAUh@M"
            + "d@I^ILOZU`@INKRMVi@`ASd@GLM`@\"},\"start_location\" : { \"lat\" : 47"
            + ".832290, \"lng\" : -122.26450},\"travel_mode\" : \"BICYCLING\" }, {\"d"
            + "istance\" : { \"text\" : \"0.1 mi\", \"value\" : 199},\"duration\" : { \"t"
            + "ext\" : \"1 min\", \"value\" : 35},\"end_location\" : { \"lat\" : 47.836180"
            + "00000001, \"lng\" : -122.270230},\"html_instructions\" : \"Keep \\u003cb"
            + "\\u003eright\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban Tra"
            + "il\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"}v}bHvpgiVOPMNMN"
            + "QXOVINGJeCxDEHY`@\"},\"start_location\" : { \"lat\" : 47.834870, \"l"
            + "ng\" : -122.268440},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" "
            + ": { \"text\" : \"0.6 mi\", \"value\" : 987},\"duration\" : { \"text\""
            + " : \"5 mins\", \"value\" : 307},\"end_location\" : { \"lat\" : 47.835"
            + "770, \"lng\" : -122.258520},\"html_instructions\" : \"Turn \\u003cb"
            + "\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003e177th Pl SW/Interur"
            + "ban Trail/Maple Rd\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em"
            + "\\\"\\u003eContinue to follow Interurban Trail/Maple Rd\\u003c/div"
            + "\\u003e\",\"polyline\" : { \"points\" : \"c_~bH|{giVO_AMs@Ig@AKIk@?Y"
            + "?UDODYj@kAnAoCnAcCv@}AdA{BNYFQRs@DQ@MDUB]Bi@?i@Aa@EyAGiBEyAC]CWG_@I_@"
            + "SaACK?CAA?CUgA?AMk@SeAAEMq@Ic@Kk@iBcJ\"},\"start_location\" : { \"lat"
            + "\" : 47.83618000000001, \"lng\" : -122.270230},\"travel_mode\" : \"BI"
            + "CYCLING\" }, {\"distance\" : { \"text\" : \"344 ft\", \"value\" : 105"
            + "},\"duration\" : { \"text\" : \"1 min\", \"value\" : 23},\"end_locatio"
            + "n\" : { \"lat\" : 47.834850, \"lng\" : -122.258820},\"html_instructions"
            + "\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eBut"
            + "ternut Rd/Interurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"point"
            + "s\" : \"q|}bHvreiVX@^?x@\\\\HBx@V\"},\"start_location\" : { \"lat\" : 4"
            + "7.835770, \"lng\" : -122.258520},\"travel_mode\" : \"BICYCLING\" }, {\""
            + "distance\" : { \"text\" : \"0.2 mi\", \"value\" : 348},\"duration\" :"
            + " { \"text\" : \"2 mins\", \"value\" : 93},\"end_location\" : { \"lat\""
            + " : 47.83680, \"lng\" : -122.259940},\"html_instructions\" : \"Turn "
            + "\\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eInterurban "
            + "Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"yv}bHrteiVAJ"
            + "El@InCAd@?V?T?J?NAN?FCFIPGFA?C@E@C@ICIEc@Yu@s@OMKEwAUaBWE?\"},\"star"
            + "t_location\" : { \"lat\" : 47.834850, \"lng\" : -122.258820},\"trave"
            + "l_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.9 mi\","
            + " \"value\" : 1452},\"duration\" : { \"text\" : \"7 mins\", \"value\" "
            + ": 409},\"end_location\" : { \"lat\" : 47.84555000000001, \"lng\" : "
            + "-122.251340},\"html_instructions\" : \"Slight \\u003cb\\u003eleft"
            + "\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban Trail\\u003c/"
            + "b\\u003e\",\"polyline\" : { \"points\" : \"_c~bHr{eiVC?EB[JGBGAeAKyB"
            + "]SKg@c@GEIEue@}HeCc@QIKOGWCc@AaAAmH@wBAsBEsNA{A\"},\"start_location"
            + "\" : { \"lat\" : 47.83680, \"lng\" : -122.259940},\"travel_mode\" :"
            + " \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.3 mi\", \"value\""
            + " : 465},\"duration\" : { \"text\" : \"1 min\", \"value\" : 83},\"end"
            + "_location\" : { \"lat\" : 47.849720, \"lng\" : -122.251610},\"html_in"
            + "structions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto "
            + "\\u003cb\\u003e13th Ave W\\u003c/b\\u003e\",\"polyline\" : { \"p"
            + "oints\" : \"uy_cHzediVQ@y@FE@yF`@}B@yA@oC@Y?O?cB@\"},\"start_loca"
            + "tion\" : { \"lat\" : 47.84555000000001, \"lng\" : -122.251340},\""
            + "travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0."
            + "3 mi\", \"value\" : 431},\"duration\" : { \"text\" : \"2 mins\", "
            + "\"value\" : 97},\"end_location\" : { \"lat\" : 47.85353000000001,"
            + " \"lng\" : -122.251060},\"html_instructions\" : \"Continue onto "
            + "\\u003cb\\u003eMeadow Rd\\u003c/b\\u003e\",\"polyline\" : { \""
            + "points\" : \"ws`cHpgdiV_F@{GFi@EYGoDcBIE\"},\"start_location\" : "
            + "{ \"lat\" : 47.849720, \"lng\" : -122.251610},\"travel_mode\" : "
            + "\"BICYCLING\" }, {\"distance\" : { \"text\" : \"2.5 mi\", \"valu"
            + "e\" : 3958},\"duration\" : { \"text\" : \"12 mins\", \"value\" : "
            + "727},\"end_location\" : { \"lat\" : 47.88039000000001, \"lng\" : "
            + "-122.228360},\"html_instructions\" : \"Turn \\u003cb\\u003eleft"
            + "\\u003c/b\\u003e onto \\u003cb\\u003eInterurban Trail\\u003c/b"
            + "\\u003e\",\"polyline\" : { \"points\" : \"qkacHbddiVi@vBW~@Wl@"
            + "c@vAWbAGR?BK^GNIFMBKASMqC{B}BkB{E{DoDwCiCwBwC_CeDqCuCaCgFgEyDaD"
            + "}AmA_Aq@ECOIaDeAg@M}AYmc@{GaBWQCS@SJQFS?yBq@iA_@i@Ua@Yc@_@MKQMY"
            + "MYK{@i@[_@IKEOOi@GQKS_AmAY[SI]K[]We@Qa@Qe@k@_AOQOGMIKCQUsD{EsCa"
            + "EMWGUEMGUcC_DcBcCc@m@SUIKIMEMEMAQAQ?kD?q@@Q@IFQEMAGAK?gABkM@mE?Q"
            + "A[?CASAOASCQEQI]Um@\"},\"start_location\" : { \"lat\" : 47.85353"
            + "000000001, \"lng\" : -122.251060},\"travel_mode\" : \"BICYCLING\""
            + " }, {\"distance\" : { \"text\" : \"0.1 mi\", \"value\" : 198},\"d"
            + "uration\" : { \"text\" : \"1 min\", \"value\" : 81},\"end_location"
            + "\" : { \"lat\" : 47.882110, \"lng\" : -122.228030},\"html_instruct"
            + "ions\" : \"Continue straight onto \\u003cb\\u003e3rd Ave SE\\u003c"
            + "/b\\u003e\",\"polyline\" : { \"points\" : \"msfcHfv_iVe@a@OMQIOEOC"
            + "SCaEBY@\"},\"start_location\" : { \"lat\" : 47.88039000000001, \"l"
            + "ng\" : -122.228360},\"travel_mode\" : \"BICYCLING\" }, {\"distance"
            + "\" : { \"text\" : \"0.6 mi\", \"value\" : 940},\"duration\" : { \""
            + "text\" : \"3 mins\", \"value\" : 178},\"end_location\" : { \"lat\""
            + " : 47.88668000000001, \"lng\" : -122.228820},\"html_instructions\""
            + " : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003"
            + "eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" "
            + ": \"e~fcHdt_iV?\\\\@Z?`@@N@J@NDV?D?J?X?t@?jA?hB?|BAhAAXCRAJGXCDCB"
            + "E@E?G@GAIAOEUEk@Sa@Sw@u@{@oAiAcBuAsByAqCo@qAQ]Q]IECAE?GHGL[p@]t@_"
            + "@t@[p@CDA@E@C?A?cB{BEECAC?C?GJ\"},\"start_location\" : { \"lat\" : "
            + "47.882110, \"lng\" : -122.228030},\"travel_mode\" : \"BICYCLING\" "
            + "}, {\"distance\" : { \"text\" : \"0.8 mi\", \"value\" : 1309},\"du"
            + "ration\" : { \"text\" : \"4 mins\", \"value\" : 244},\"end_location"
            + "\" : { \"lat\" : 47.89573000000001, \"lng\" : -122.217620},\"html_"
            + "instructions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e to st"
            + "ay on \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline"
            + "\" : { \"points\" : \"wzgcHby_iVKOgAaBgAuAeCoDaIqKgHuJAAsQqVeEwFYY"
            + "q@e@]S\"},\"start_location\" : { \"lat\" : 47.88668000000001, \"ln"
            + "g\" : -122.228820},\"travel_mode\" : \"BICYCLING\" }, {\"distance\""
            + " : { \"text\" : \"0.7 mi\", \"value\" : 1047},\"duration\" : { \"te"
            + "xt\" : \"3 mins\", \"value\" : 194},\"end_location\" : { \"lat\" : "
            + "47.90486000000001, \"lng\" : -122.216370},\"html_instructions\" : "
            + "\"Slight \\u003cb\\u003eright\\u003c/b\\u003e to stay on \\u003cb"
            + "\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"poin"
            + "ts\" : \"isicHbs}hVGMEGMOQSSUMQGIEGMSCCCCYQKEGEEAG?E?E@E@MFIBG@O@"
            + "k@AWGuFuBOEYEc@?mFFy\\\\d@\"},\"start_location\" : { \"lat\" : 47."
            + "89573000000001, \"lng\" : -122.217620},\"travel_mode\" : \"BICYCLI"
            + "NG\" }, {\"distance\" : { \"text\" : \"0.3 mi\", \"value\" : 529},"
            + "\"duration\" : { \"text\" : \"2 mins\", \"value\" : 91},\"end_loc"
            + "ation\" : { \"lat\" : 47.905610, \"lng\" : -122.223240},\"html_ins"
            + "tructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto "
            + "\\u003cb\\u003eBruskrud Rd\\u003c/b\\u003e\",\"polyline\" : { \"poi"
            + "nts\" : \"klkcHhk}hVAP?L?F?`@CfDCzBAl@AXA\\\\It@Ej@Gl@Ef@C^Al@C|@Gp"
            + "@E\\\\ERG^eA|EId@C`@@V@PBPLz@?JCV\"},\"start_location\" : { \"lat\" "
            + ": 47.90486000000001, \"lng\" : -122.216370},\"travel_mode\" : \"BIC"
            + "YCLING\" }, {\"distance\" : { \"text\" : \"1.2 mi\", \"value\" : 1899"
            + "},\"duration\" : { \"text\" : \"7 mins\", \"value\" : 448},\"end_loc"
            + "ation\" : { \"lat\" : 47.922350, \"lng\" : -122.223150},\"html_instruc"
            + "tions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb"
            + "\\u003e7th Ave SE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : "
            + "\"aqkcHfv~hViB?m@B_BBqB@u@AI?K?_@?gB?[?i@?i@?O?}A@cA?}@@q@@I?qA@yA"
            + "@aA@c@@sA?S@cBDoAAsA?uABaB@aDBwE?aDDwAF_A?OIKYEWA_@C_@gA@cB@wB@_@?m"
            + "@?iIDa@?U@QHIFST\"},\"start_location\" : { \"lat\" : 47.905610, \"l"
            + "ng\" : -122.223240},\"travel_mode\" : \"BICYCLING\" }, {\"distance\""
            + " : { \"text\" : \"443 ft\", \"value\" : 135},\"duration\" : { \"text"
            + "\" : \"1 min\", \"value\" : 25},\"end_location\" : { \"lat\" : 47.92"
            + "301000000001, \"lng\" : -122.221630},\"html_instructions\" : \"Turn "
            + "\\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eE Casino Rd"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"uyncHtu~hVUs@Y{@M"
            + "_@Ma@?Ai@_BKYAA\"},\"start_location\" : { \"lat\" : 47.922350, \"lng"
            + "\" : -122.223150},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" :"
            + " { \"text\" : \"0.8 mi\", \"value\" : 1251},\"duration\" : { \"text\" "
            + ": \"3 mins\", \"value\" : 175},\"end_location\" : { \"lat\" : 47.92810, "
            + "\"lng\" : -122.21140},\"html_instructions\" : \"Turn \\u003cb\\u003erigh"
            + "t\\u003c/b\\u003e onto \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e"
            + "\",\"polyline\" : { \"points\" : \"y}ncHdl~hVHKAA?E?CF_@j@qITaDJuABy@?"
            + "o@DqBA{@?M@}A?iD?kABQJc@F[@[?sAEa@GYIUKMc@Y}EuBaBw@mB{@uB_Ay@_@sAc@mAS"
            + "uD]}AIIAMMGK\"},\"start_location\" : { \"lat\" : 47.92301000000001, \""
            + "lng\" : -122.221630},\"travel_mode\" : \"BICYCLING\" }, {\"distance\""
            + " : { \"text\" : \"0.5 mi\", \"value\" : 849},\"duration\" : { \"text\" "
            + ": \"2 mins\", \"value\" : 142},\"end_location\" : { \"lat\" : 47.934780"
            + ", \"lng\" : -122.20710},\"html_instructions\" : \"Slight \\u003cb\\u003"
            + "eleft\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban Trail\\u003c/b"
            + "\\u003e\",\"polyline\" : { \"points\" : \"s}ocHfl|hVMMC?C@OFm@NI?I?m@Mi"
            + "@U_@ISCO@]JQ@y@I}AWuA]o@SyAo@yA{@gAeAq@q@OMqJaLDM?EAGEKCECCOMYWAE\"},\""
            + "start_location\" : { \"lat\" : 47.92810, \"lng\" : -122.21140},\"travel"
            + "_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"144 ft\", \"v"
            + "alue\" : 44},\"duration\" : { \"text\" : \"1 min\", \"value\" : 8},\"en"
            + "d_location\" : { \"lat\" : 47.935160, \"lng\" : -122.207020},\"html_inst"
            + "ructions\" : \"Slight \\u003cb\\u003eleft\\u003c/b\\u003e to stay on "
            + "\\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : "
            + "{ \"points\" : \"kgqcHjq{hVMAO?S?MAEAEI\"},\"start_location\" : "
            + "{ \"lat\" : 47.934780, \"lng\" : -122.20710},\"travel_mode\" : \"B"
            + "ICYCLING\" }, {\"distance\" : { \"text\" : \"495 ft\", \"value\" : "
            + "151},\"duration\" : { \"text\" : \"1 min\", \"value\" : 19},\"end_l"
            + "ocation\" : { \"lat\" : 47.936170, \"lng\" : -122.205710},\"html_i"
            + "nstructions\" : \"Slight \\u003cb\\u003eright\\u003c/b\\u003e to s"
            + "tay on \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polylin"
            + "e\" : { \"points\" : \"wiqcHzp{hVO]KS}BoCe@i@CAAAACAC?M\"},\"sta"
            + "rt_location\" : { \"lat\" : 47.935160, \"lng\" : -122.207020},\"tr"
            + "avel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0."
            + "8 mi\", \"value\" : 1256},\"duration\" : { \"text\" : \"3 mins\""
            + ", \"value\" : 207},\"end_location\" : { \"lat\" : 47.946370, \"l"
            + "ng\" : -122.200860},\"html_instructions\" : \"Turn \\u003cb\\u003e"
            + "left\\u003c/b\\u003e onto \\u003cb\\u003eCommercial Ave/Interur"
            + "ban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"ap"
            + "qcHth{hVC?OASGKGMQe@i@kAoAcDuDkDsDmD_EiDmDk@]e@YSKgAg@eB_@eAKiA"
            + "G[A]?Q?UD_@D]@kAEoBIMCeAE{@?iAFo@Jc@He@Ng@R_@V\"},\"start_locat"
            + "ion\" : { \"lat\" : 47.936170, \"lng\" : -122.205710},\"travel_"
            + "mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.1 mi"
            + "\", \"value\" : 231},\"duration\" : { \"text\" : \"1 min\", \"val"
            + "ue\" : 51},\"end_location\" : { \"lat\" : 47.948160, \"lng"
            + "\" : -122.201630},\"html_instructions\" : \"Turn \\u003cb\\u003e"
            + "right\\u003c/b\\u003e onto \\u003cb\\u003eInterurban Trail\\u003"
            + "c/b\\u003e\",\"polyline\" : { \"points\" : \"yoscHjjzhVCMC?c@RgB"
            + "nAa@^[^YVe@TQLG@E?CCECIKGIEIGGAAGG\"},\"start_location\" : { \"lat"
            + "\" : 47.946370, \"lng\" : -122.200860},\"travel_mode\" : \"BICYCL"
            + "ING\" }, {\"distance\" : { \"text\" : \"0.2 mi\", \"value\" : 277"
            + "},\"duration\" : { \"text\" : \"1 min\", \"value\" : 38},\"end_lo"
            + "cation\" : { \"lat\" : 47.949770, \"lng\" : -122.204270},\"html_ins"
            + "tructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e to stay o"
            + "n \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" :"
            + " { \"points\" : \"_{scHdozhVQRo@z@wApBa@d@GJGNERAT?n@?PCPSd@uAfB\""
            + "},\"start_location\" : { \"lat\" : 47.948160, \"lng\" : -122.201630"
            + "},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \""
            + "0.1 mi\", \"value\" : 175},\"duration\" : { \"text\" : \"1 min\", \""
            + "value\" : 51},\"end_location\" : { \"lat\" : 47.95110, \"lng\" : -1"
            + "22.205510},\"html_instructions\" : \"Continue onto \\u003cb\\u003e"
            + "Alta Dr\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"aetcHt_{h"
            + "VaAjAYXWVu@h@_Al@]\\\\AB\"},\"start_location\" : { \"lat\" : 47.949"
            + "770, \"lng\" : -122.204270},\"travel_mode\" : \"BICYCLING\" }, {\"dist"
            + "ance\" : { \"text\" : \"0.6 mi\", \"value\" : 935},\"duration\" : { "
            + "\"text\" : \"3 mins\", \"value\" : 151},\"end_location\" : { \"lat\" "
            + ": 47.95941000000001, \"lng\" : -122.207220},\"html_instructions\" : "
            + "\"Slight \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eIn"
            + "terurban Trail\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em"
            + "\\\"\\u003eRestricted usage road\\u003c/div\\u003e\",\"polyline\" "
            + ": { \"points\" : \"kmtcHlg{hVUCCAC?C@_@FaARGBE@aCTG?I@_Ep@yARsKz@gC"
            + "PiBRk@DoB\\\\wBb@GBGBWLGBk@Jo@HW?\"},\"start_location\" : { \"lat\""
            + " : 47.95110, \"lng\" : -122.205510},\"travel_mode\" : \"BICYCLING\""
            + " }, {\"distance\" : { \"text\" : \"0.3 mi\", \"value\" : 467},\"du"
            + "ration\" : { \"text\" : \"2 mins\", \"value\" : 124},\"end_locatio"
            + "n\" : { \"lat\" : 47.96331000000001, \"lng\" : -122.20790},\"html_"
            + "instructions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e to sta"
            + "y on \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline"
            + "\" : { \"points\" : \"iavcHbr{hVG@C@?B?J@f@?LCFC@E@gDDgA@OAC?C@A@C"
            + "?GCOCI?SBO?I@S@kADw@BEA]E[Eu@D{ABE@E?E@A@C@SX\"},\"start_locatio"
            + "n\" : { \"lat\" : 47.95941000000001, \"lng\" : -122.207220},\""
            + "travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \""
            + "1.1 mi\", \"value\" : 1772},\"duration\" : { \"text\" : \"6 mins"
            + "\", \"value\" : 331},\"end_location\" : { \"lat\" : 47.979240, \""
            + "lng\" : -122.20860},\"html_instructions\" : \"Slight \\u003cb"
            + "\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eColby Ave\\u003c"
            + "/b\\u003e\",\"polyline\" : { \"points\" : \"uyvcHjv{hVmGNkGHcGLgG"
            + "LgGDcGJkGLgGHaGLmGHgGNsGB\"},\"start_location\" : { \"lat\" : 47."
            + "96331000000001, \"lng\" : -122.20790},\"travel_mode\" : \"BICYCL"
            + "ING\" }, {\"distance\" : { \"text\" : \"0.3 mi\", \"value\" : 48"
            + "7},\"duration\" : { \"text\" : \"1 min\", \"value\" : 74},\"end_l"
            + "ocation\" : { \"lat\" : 47.97922000000001, \"lng\" : -122.202080"
            + "},\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u003c/b"
            + "\\u003e onto \\u003cb\\u003eHewitt Ave\\u003c/b\\u003e\\u003cdiv"
            + " style=\\\"font-size:0.9em\\\"\\u003eDestination will be on the"
            + " right\\u003c/div\\u003e\",\"polyline\" : { \"points\" : \"g}y"
            + "cHvz{hV?uGDwG?{GFuG?_AI]?yA\"},\"start_location\" : { \"lat\" :"
            + " 47.979240, \"lng\" : -122.20860},\"travel_mode\" : \"BICYCLIN"
            + "G\" }],\"via_waypoint\" : [] }],\"overview_polyline\" : { \"p"
            + "oints\" : \"eq|aHvtriV?h@qC?aHCiQI}TKqHGwCAAr@uH`HaBh@sA^Gg@Q"
            + "aAI]m@sAy@_A_B_AcAKsAVoB|AgG`LqAnFMrEPrEYzEkBzE_KdK{@|Ag@lDLpD"
            + "bDvI?v\\\\Bd`@?tNkA?oCHqCPwIFuXFs`ATyWHkJB@wQ@Yq@OuVcHsAS}BJs@"
            + "Rk@I}TpAuCf@{AHmCEyCk@gHe@o@V[e@e@GqCO}DWcOeAiTDiLAkJF?Z]AWM}"
            + "Bc@i]qHgFkBs@AkBJiDR{BMs@RfAp@[s@UaCW]}Ci@qAg@}AIcCEsLI}Ai@eOE"
            + "iIAaATyBTcAPiAKsCOw@DqBH{EjAaAv@{EnAsDx@gFDUc@]GId@w@QoB]oF^[i"
            + "@E}Fa@?kBQyDHuN?k@s@w@m@mI}EiB{@eBa@wIaDmGuAwBA?aQAuOmUJcQDmG@"
            + "yBKQ_@a@u@cDuE_Ae@cDe@}LSqEIgEs@gE}AcHcDcCgAe@Ie@kAsBq@}@AqC_A"
            + "aEkAmFTwBUsGAqFAeDW_Ba@qCgBqDwFqBsHCyAm@YcOuj@kAaDs@mCW@MXGdAs"
            + "DBEsMi@]oA@E}AJo@`AiAv@{@eCuJmBuKgC}Ow@}EIq@[@SDOQ?cPA]sB?yOar"
            + "@_AuCq@EcCuBaAw@sACQg@TcAt@n@VCNo@XyBCq@oE{JgHuO}CoGaB{EiEaIc"
            + "FcLsHyR}`@w~@oDaEaCcAqCuBmBqCa@CYh@W[oAyA}Ao@wAVy@f@aF|IsB~Em"
            + "C`Fs@lAkCbEY`@O_AW{AKw@JyAtJySPsACoEUyFi@mC{@kEmCeN|Bb@v@b@O|D"
            + "A~A]jAsCgBcEm@q@P_Ei@{@o@mj@mJi@uAC{QGoQkAHwMf@}Y?yDiBaAvD{A|E]z@_E"
            + "gCoi@sc@}IeHwHwBug@uHe@RmCq@yDoBsAs@gBeBcB}CgBoAgBmDy@g@gJkMyCyEeDs"
            + "EW{@?aGD_XQmCuA{BeAW{ED@x@DlADlLIbCUd@sCu@sG}ImD_H[@aBjDg@z@oBaCSHa"
            + "HwJ_e@{n@_FqGoAy@m@y@o@y@qA{@mBPwHiCqGF{\\\\v@C~EI`Fo@tJyAnHIpBLpBiJ"
            + "HcIAc_@V}RJwCF[c@Gw@C_@gA@{EBmA?sKP]\\\\o@oBeAcDEi@xA}UTeQBmDaAwAc"
            + "PiHmCcAcGq@}Be@e@CoB@mBa@o@LwCa@eCq@sDkB{NgPAg@q@o@s@G}E{FEWs@QcHa"
            + "IoP_QgFmBiEUeBLoGYyE\\\\qBl@_H~Ew@m@kAdAiCrDGjBoDjFgDhCy@ZaGx@ea@l"
            + "E{GrAQrAcMPuG@_@^e`@t@kaAtAL_b@IwD\"},\"summary\" : \"Interurban T"
            + "rail\",\"warnings\" : [ \"Bicycling directions are in beta. Use cau"
            + "tion \u2013 This route may contain streets that aren\'t suited for "
            + "bicycling.\"],\"waypoint_order\" : [] }, {\"bounds\" : { \"northea"
            + "st\" : {\"lat\" : 47.979240,\"lng\" : -122.200410 }, \"southwest\""
            + " : {\"lat\" : 47.664990,\"lng\" : -122.325610 }},\"copyrights\" : "
            + "\"Map data \u00a92013 Google\",\"legs\" : [ {\"distance\" : { \"t"
            + "ext\" : \"29.7 mi\", \"value\" : 47774},\"duration\" : { \"text\" "
            + ": \"2 hours 49 mins\", \"value\" : 10117},\"end_address\" : \"Ever"
            + "ett, WA, USA\",\"end_location\" : { \"lat\" : 47.97922000000001, "
            + "\"lng\" : -122.202080},\"start_address\" : \"302 Northeast 50th"
            + " Street, Seattle, WA 98105, USA\",\"start_location\" : { \"lat"
            + "\" : 47.664990, \"lng\" : -122.32540},\"steps\" : [ {\"distanc"
            + "e\" : { \"text\" : \"52 ft\", \"value\" : 16},\"duration\" : {"
            + " \"text\" : \"1 min\", \"value\" : 6},\"end_location\" : { \"l"
            + "at\" : 47.664990, \"lng\" : -122.325610},\"html_instructions\""
            + " : \"Head \\u003cb\\u003ewest\\u003c/b\\u003e on \\u003cb\\u003e"
            + "NE 50th St\\u003c/b\\u003e toward \\u003cb\\u003eLatona Ave NE"
            + "\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"eq|aHvtriV?"
            + "h@\"},\"start_location\" : { \"lat\" : 47.664990, \"lng\" : -1"
            + "22.32540},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : "
            + "{ \"text\" : \"0.8 mi\", \"value\" : 1214},\"duration\" : { "
            + "\"text\" : \"3 mins\", \"value\" : 187},\"end_location\" : { "
            + "\"lat\" : 47.67590000000001, \"lng\" : -122.325430},\"html_in"
            + "structions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e o"
            + "nto \\u003cb\\u003eLatona Ave NE\\u003c/b\\u003e\",\"polyline"
            + "\" : { \"points\" : \"eq|aH`vriVqC?oCAqCAqCEqC?qC?sCCsCAoCCmC"
            + "?MAKAwAAmAAkA@mACiA?mAAkAAwCA\"},\"start_location\" : { \"lat"
            + "\" : 47.664990, \"lng\" : -122.325610},\"travel_mode\" : \"BIC"
            + "YCLING\" }, {\"distance\" : { \"text\" : \"1.6 mi\", \"value\""
            + " : 2633},\"duration\" : { \"text\" : \"15 mins\", \"value\" : 9"
            + "04},\"end_location\" : { \"lat\" : 47.67579000000001, \"lng\" :"
            + " -122.290270},\"html_instructions\" : \"Turn \\u003cb\\u003erig"
            + "ht\\u003c/b\\u003e onto \\u003cb\\u003eNE 65th St\\u003c/b\\u003e\""
            + ",\"polyline\" : { \"points\" : \"ku~aH|triV@qE@gE?w@?u@?cB@eB?"
            + "kB?a@?G?gA?A@s@?A?kA?eC@iC@oA?]?o@BgB?qCAuA?qB@oB@y@?{@?]@{B?wB?{"
            + "B@cA?o@AwE?uEAkBAiBAuEAqC@C?M?I@G?G@E@I@Q@qE?aA?qC?wB?_C?q@?e@@wE?kE"
            + "AqE?oE?[?yD?[?uD?]?sD?w@?}C?u@?{C?y@AaB@u@?sB?cBA]?kC\"},\"star"
            + "t_location\" : { \"lat\" : 47.67590000000001, \"lng\" : -122.32"
            + "5430},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"t"
            + "ext\" : \"1.5 mi\", \"value\" : 2411},\"duration\" : { \"text\""
            + " : \"8 mins\", \"value\" : 474},\"end_location\" : { \"lat\" : 4"
            + "7.697470, \"lng\" : -122.290550},\"html_instructions\" : \"Turn"
            + " \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003e35th "
            + "Ave NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"ut~aHd"
            + "ykiVkEB]@aC@sHHu@@Y?oIHo@@gA@E?U?cA@M?uA@o@@iJJaDDgEBaDD{BBcA@s"
            + "A@_BD[@O@K?K?Y?O@W?i@B]AWAwAAoCAoCGsCCoCCoCAe@As@Aw@?gAAeA?qB?_@"
            + "A[?c@A]@w@A\"},\"start_location\" : { \"lat\" : 47.6757900000000"
            + "1, \"lng\" : -122.290270},\"travel_mode\" : \"BICYCLING\" }, "
            + "{\"distance\" : { \"text\" : \"0.5 mi\", \"value\" : 789},\"d"
            + "uration\" : { \"text\" : \"2 mins\", \"value\" : 117},\"end_lo"
            + "cation\" : { \"lat\" : 47.69738000000001, \"lng\" : -122.28001"
            + "0},\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u003c"
            + "/b\\u003e onto \\u003cb\\u003eNE 95th St\\u003c/b\\u003e\",\"pol"
            + "yline\" : { \"points\" : \"e|bbH|zkiV?y@?q@?w@@wD@eED}N@yD?eB@qC?"
            + "qA@oC?}B@iG\"},\"start_location\" : { \"lat\" : 47.697470, \"lng"
            + "\" : -122.290550},\"travel_mode\" : \"BICYCLING\" }, {\"distance"
            + "\" : { \"text\" : \"249 ft\", \"value\" : 76},\"duration\" : { \""
            + "text\" : \"1 min\", \"value\" : 20},\"end_location\" : { \"lat\""
            + " : 47.696690, \"lng\" : -122.280010},\"html_instructions\" : \"Tu"
            + "rn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003e45t"
            + "h Ave NE\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"s{bb"
            + "H`yiiV\\\\?j@?~@?\"},\"start_location\" : { \"lat\" : 47.6973800"
            + "0000001, \"lng\" : -122.280010},\"travel_mode\" : \"BICYCLING\" "
            + "}, {\"distance\" : { \"text\" : \"0.1 mi\", \"value\" : 183},\"du"
            + "ration\" : { \"text\" : \"1 min\", \"value\" : 29},\"end_location"
            + "\" : { \"lat\" : 47.69610, \"lng\" : -122.277910},\"html_instruct"
            + "ions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e onto \\u003cb"
            + "\\u003eNE 94th St\\u003c/b\\u003e\",\"polyline\" : { \"points\""
            + " : \"iwbbH`yiiVJoBDqADoA@M@KBI@EDGFGJMJMJIBEBABA@?@?@?Ng@\"},\"st"
            + "art_location\" : { \"lat\" : 47.696690, \"lng\" : -122.280010},\"tr"
            + "avel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"1.9 "
            + "mi\", \"value\" : 3010},\"duration\" : { \"text\" : \"10 mins\", "
            + "\"value\" : 596},\"end_location\" : { \"lat\" : 47.72067000000001"
            + ", \"lng\" : -122.281170},\"html_instructions\" : \"Turn \\u003cb"
            + "\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003eBurke-Gilman Tra"
            + "il\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"ssbbH|kiiV"
            + "MOIIGIKMMSKMEGEKOi@IWOg@UiAWuA[{AMg@EQIYg@uAGSGKOYe@w@OUIMEEEEW"
            + "UWWSOQOSOQKOGQIYKQGSEc@IQCOAW?OAW@]BSDMBUD[HSFQFa@NOFSFs@Tw@V{@"
            + "X[HcAXy@XsA`@[JYH]LYHSFKDeA\\\\gBj@kA^{Af@i@LYFOBO@M?M@I?w@Eu@C"
            + "m@EUAU?_@@a@Dg@Hq@T_Bd@wBp@uDjAm@TaAVeAVQBOBs@J_@Dm@BcFVKBK@SDW"
            + "Hi@LaCh@uBf@k@PsFvAkCr@kBb@_ATeAXeAV{@Rc@LSJe@XMLIHWXm@z@}@rAc@"
            + "l@UV_@^QPQLMHMFSHUF\"},\"start_location\" : { \"lat\" : 47.6961"
            + "0, \"lng\" : -122.277910},\"travel_mode\" : \"BICYCLING\" }, {\"d"
            + "istance\" : { \"text\" : \"3.3 mi\", \"value\" : 5248},\"duratio"
            + "n\" : { \"text\" : \"17 mins\", \"value\" : 1017},\"end_location"
            + "\" : { \"lat\" : 47.75797000000001, \"lng\" : -122.262420},\"h"
            + "tml_instructions\" : \"Slight \\u003cb\\u003eright\\u003c/b"
            + "\\u003e to stay on \\u003cb\\u003eBurke-Gilman Trail\\u003c"
            + "/b\\u003e\",\"polyline\" : { \"points\" : \"emgbHh`jiVe@Js@L"
            + "mDf@e@Fa@@O?UCYA]GYIa@K{A]}@UqA]y@S_@Kc@Io@Ic@E[?qAFmBd@WLoG"
            + "tCiAh@iAh@SFWJQDw@LK@K@g@@e@Eu@I_Da@MCO?]B[DSDUJWJQJQJQLSPST"
            + "STU\\\\]l@Wf@Wb@Yd@OVk@v@g@j@]Vq@^QJa@F}@PoATYHUHEB}Az@}AbAs"
            + "@`@aB|@SJSFeAVQ@M@G?yAGGAGAGCQEkAg@QOoGiEw@c@YK]Ky@MQCeBC{C"
            + "By@?kBGK@UEa@E_BSqBS_BWs@I{CY}AW_Bg@gEkBuOwGeBkAo@s@k@y@a@w@Wq@K"
            + "EGCIMEOGKCM?K?IBO?A?AkBeGu@cCgB}FEECCGACCCIKYI_@EMCKCMAG?G?IAC?E"
            + "ACu@_CeBgEyE{JKQIKqAeBeCuCIMIMMUKSSc@Oe@Me@GQIc@G]Ea@Gg@Gm@]uDa@{"
            + "EKgAi@iFEg@AM?_@?K?W?QDcCDqH\"},\"start_location\" : { \"lat\" : "
            + "47.72067000000001, \"lng\" : -122.281170},\"travel_mode\" : \"BIC"
            + "YCLING\" }, {\"distance\" : { \"text\" : \"0.9 mi\", \"value\" : 14"
            + "20},\"duration\" : { \"text\" : \"4 mins\", \"value\" : 241},\"end_"
            + "location\" : { \"lat\" : 47.757260, \"lng\" : -122.243670},\"html_i"
            + "nstructions\" : \"Slight \\u003cb\\u003eright\\u003c/b\\u003e to s"
            + "tay on \\u003cb\\u003eBurke-Gilman Trail\\u003c/b\\u003e\",\"polyl"
            + "ine\" : { \"points\" : \"ivnbHbkfiV?Y@M@I@C@A@C?C?_@Ao@?a@Ai@EyBQw"
            + "FWsHQqFKcEIkC?a@@uA@_D@_@?KAIAGCMAKAG?K@]?M?I?MBeBBaB@c@@S@Q@Y@S@O"
            + "@YD_ABo@@e@Bi@@K?E?G@K?G@C@WDe@@QXqD^{Dp@wGVeD?cAh@}F\"},\"start_l"
            + "ocation\" : { \"lat\" : 47.75797000000001, \"lng\" : -122.262420},"
            + "\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \""
            + "0.8 mi\", \"value\" : 1270},\"duration\" : { \"text\" : \"5 mins\""
            + ", \"value\" : 315},\"end_location\" : { \"lat\" : 47.768430, \"lng"
            + "\" : -122.242310},\"html_instructions\" : \"Turn \\u003cb\\u003el"
            + "eft\\u003c/b\\u003e onto \\u003cb\\u003e73rd Ave NE\\u003c/b\\u003e"
            + "\",\"polyline\" : { \"points\" : \"{qnbH|ubiVG?I?QAoIFQ?qGF{A@YAw@G"
            + "UEa@IeAY_@Qi@]IGeCuBe@]_@Qi@GwHd@oBNq@DkBLmBBi@CQEc@GOEKC{Bw@\"},\""
            + "start_location\" : { \"lat\" : 47.757260, \"lng\" : -122.243670"
            + "},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\""
            + " : \"0.4 mi\", \"value\" : 700},\"duration\" : { \"text\" : \"2"
            + " mins\", \"value\" : 112},\"end_location\" : { \"lat\" : 47.767"
            + "140, \"lng\" : -122.233330},\"html_instructions\" : \"Turn "
            + "\\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eNE "
            + "192nd St\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"u"
            + "wpbHlmbiVXwBBc@`@sHBe@BUJg@vAwFh@yB@GZqAJm@@G?GBq@A_GAqG?a"
            + "C\"},\"start_location\" : { \"lat\" : 47.768430, \"lng\" : "
            + "-122.242310},\"travel_mode\" : \"BICYCLING\" }, {\"distance"
            + "\" : { \"text\" : \"0.7 mi\", \"value\" : 1077},\"duration\""
            + " : { \"text\" : \"7 mins\", \"value\" : 431},\"end_location"
            + "\" : { \"lat\" : 47.776820, \"lng\" : -122.233010},\"html_in"
            + "structions\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e ont"
            + "o \\u003cb\\u003e80th Ave NE\\u003c/b\\u003e\",\"polyline\" :"
            + " { \"points\" : \"sopbHhu`iV_AAmDEc@AaEEYAeGGwFGcCCoAAsACoGMa"
            + "EA{CAMA\"},\"start_location\" : { \"lat\" : 47.767140, \"lng\""
            + " : -122.233330},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" "
            + ": { \"text\" : \"0.2 mi\", \"value\" : 400},\"duration\" : { \"tex"
            + "t\" : \"3 mins\", \"value\" : 190},\"end_location\" : { \"lat\" : "
            + "47.78042000000001, \"lng\" : -122.233010},\"html_instructions\" : "
            + "\"Continue onto \\u003cb\\u003eMeridian Ave S\\u003c/b\\u003e\",\""
            + "polyline\" : { \"points\" : \"clrbHhs`iV_@?y@?wG?qC?kE?\"},\"start"
            + "_location\" : { \"lat\" : 47.776820, \"lng\" : -122.233010},\"trave"
            + "l_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.6 mi\""
            + ", \"value\" : 1008},\"duration\" : { \"text\" : \"3 mins\", \"value"
            + "\" : 177},\"end_location\" : { \"lat\" : 47.780270, \"lng\" : -122."
            + "219520},\"html_instructions\" : \"Turn \\u003cb\\u003eright\\u003c/"
            + "b\\u003e onto \\u003cb\\u003e240th St SE\\u003c/b\\u003e\",\"polyli"
            + "ne\" : { \"points\" : \"sbsbHhs`iVJgTBoKBkH@aBDkN?aL@uH\"},\"start"
            + "_location\" : { \"lat\" : 47.78042000000001, \"lng\" : -122.233010"
            + "},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" :"
            + " \"7.9 mi\", \"value\" : 12745},\"duration\" : { \"text\" : \"46 "
            + "mins\", \"value\" : 2744},\"end_location\" : { \"lat\" : 47.88772"
            + "0, \"lng\" : -122.206670},\"html_instructions\" : \"Turn \\u003"
            + "cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003eBothell Everett"
            + " Hwy\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"uasbH~~}h"
            + "VmCnBGDg@Zs@X[HSDKBK@s@JqAAq@ISEMCqBa@}Dq@KCcGcA_Cg@oBc@oBE_BB_B"
            + "KYISGSMUQ{BqBk@e@sAuAMOe@e@y@y@_@_@gAgAoAeAiA}@OMuAw@{A}@eAg@g@S"
            + "}@c@e@Uk@WgAm@QKECi@YQIWO]YuAo@_B}@{EgC{EeCKGKG}DoB{DmBoFyCkEiCmC"
            + "aBw@_@u@WUK}BcAo@e@IGk@SmAa@UEc@KUCYC_AGsECo@@E?iDAY?y@?cA?U?u@"
            + "?gCAC@QHUAqBCyCAeCC_BCqDCG?iDAoFAW?gC?qCAcGAcGCqFCcA?yK?eC@cCb@aA"
            + "XaA\\\\y@^]POF{AfAo@\\\\s@Zs@Vi@Ji@Fc@Du@B_DGaDOs@I[CkAEmACkAF}AZ"
            + "gA`@wBpAyChB}@h@}A`AgDxBuBvA]Vi@b@o@n@w@z@sAzBqAnBw@fAMNi@l@{AlA}"
            + "Av@_@N]J{@R}@JyDPE?aSfAkEXgBLiFnAgHtB{Ab@i@LYNQEYFu@ZkDlAy@P{@BsDH"
            + "M?M@sEHoCFeBHkAFaGh@gBPqAH}Kt@gF`@}ADa@AyAQuG{@SCqQyBuBGmGT{CP_CAo"
            + "CO_Ba@yBqA_@QG?gH}E{AmAaAeAcCmC{AoBgDeEqCgDm@u@[a@[i@KSAWACEQSg"
            + "@a@oBM}@WmBGg@_@qCs@sGEUCMEMEKISGMEIOSACECGAG@G?E@q@GoAA_CEwBAo"
            + "@@kBA{HI}EIwECu@As@Ac@CeHAcA?g@Ak@@\"},\"start_location\" : { \"l"
            + "at\" : 47.780270, \"lng\" : -122.219520},\"travel_mode\" : \"BICYCL"
            + "ING\" }, {\"distance\" : { \"text\" : \"0.9 mi\", \"value\" : 1406}"
            + ",\"duration\" : { \"text\" : \"4 mins\", \"value\" : 265},\"end_lo"
            + "cation\" : { \"lat\" : 47.897240, \"lng\" : -122.206710},\"html_ins"
            + "tructions\" : \"Continue onto \\u003cb\\u003eWA-527 N/19th Ave SE\\"
            + "u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eC"
            + "ontinue to follow WA-527 N\\u003c/div\\u003e\",\"polyline\" : { \"po"
            + "ints\" : \"gahcHtn{hVmEEoDAMIEAc@EGAEAKAUGc@Sa@Y}@_AyAiAODYUY]W[U"
            + "WW_@_@g@IMEKoA}BYi@OYk@w@mBuBMKSOWSWM[OUIYGSC[?SBYFa@R]NSFEBGFEB"
            + "EDEDEHEDEHCFCHGTIbCKx@?XIdHEfAIb@M^SXSX_@Ts@HeA?WBa@DQ@\"},\"sta"
            + "rt_location\" : { \"lat\" : 47.887720, \"lng\" : -122.206670},\"t"
            + "ravel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0."
            + "8 mi\", \"value\" : 1223},\"duration\" : { \"text\" : \"5 mins\","
            + " \"value\" : 281},\"end_location\" : { \"lat\" : 47.896470, \"lng\""
            + " : -122.223030},\"html_instructions\" : \"Turn \\u003cb\\u003eleft\\u"
            + "003c/b\\u003e onto \\u003cb\\u003e112th St SE\\u003c/b\\u003e\",\""
            + "polyline\" : { \"points\" : \"w|icH|n{hV?ZJtCPdBF|Ah@fMZnGR|E"
            + "Br@HtBHvB@XB~@?@?F@`B?V?vA?@?|@?R?J?T?t@AdF?tD?n@?XAxA?`FAhF?b"
            + "C\"},\"start_location\" : { \"lat\" : 47.897240, \"lng\" : -12"
            + "2.206710},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : "
            + "{ \"text\" : \"1.8 mi\", \"value\" : 2915},\"duration\" : { "
            + "\"text\" : \"10 mins\", \"value\" : 615},\"end_location\" : "
            + "{ \"lat\" : 47.922350, \"lng\" : -122.223150},\"html_instru"
            + "ctions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e ont"
            + "o \\u003cb\\u003e7th Ave SE\\u003c/b\\u003e\",\"polyline\" "
            + ": { \"points\" : \"}wicH|t~hV_B@S?}A?uB?wDDq@?[?{A@m@@c@BuA"
            + "BgD@_C@_A?wCDmCDk@@{EB{@?iB?m@B_BBqB@u@AI?K?_@?gB?[?i@?i@?O"
            + "?}A@cA?}@@q@@I?qA@yA@aA@c@@sA?S@cBDoAAsA?uABaB@aDBwE?aDDwAF"
            + "_A?OIKYEWA_@C_@gA@cB@wB@_@?m@?iIDa@?U@QHIFST\"},\"start_loc"
            + "ation\" : { \"lat\" : 47.896470, \"lng\" : -122.223030},\"t"
            + "ravel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : "
            + "\"443 ft\", \"value\" : 135},\"duration\" : { \"text\" : \"1 "
            + "min\", \"value\" : 25},\"end_location\" : { \"lat\" : 47.92301000"
            + "000001, \"lng\" : -122.221630},\"html_instructions\" : \"Turn \\u00"
            + "3cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eE Casino Rd\\u0"
            + "03c/b\\u003e\",\"polyline\" : { \"points\" : \"uyncHtu~hVUs@Y{@M_@M"
            + "a@?Ai@_BKYAA\"},\"start_location\" : { \"lat\" : 47.922350, \"lng"
            + "\" : -122.223150},\"travel_mode\" : \"BICYCLING\" }, {\"distance\""
            + " : { \"text\" : \"0.8 mi\", \"value\" : 1251},\"duration\" : { \""
            + "text\" : \"3 mins\", \"value\" : 175},\"end_location\" : { \"lat\""
            + " : 47.92810, \"lng\" : -122.21140},\"html_instructions\" : \"Turn "
            + "\\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eInterurba"
            + "n Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"y}ncHdl"
            + "~hVHKAA?E?CF_@j@qITaDJuABy@?o@DqBA{@?M@}A?iD?kABQJc@F[@[?sAEa@GY"
            + "IUKMc@Y}EuBaBw@mB{@uB_Ay@_@sAc@mASuD]}AIIAMMGK\"},\"start_locati"
            + "on\" : { \"lat\" : 47.92301000000001, \"lng\" : -122.221630},\"t"
            + "ravel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"0.5"
            + " mi\", \"value\" : 849},\"duration\" : { \"text\" : \"2 mins\", \"v"
            + "alue\" : 142},\"end_location\" : { \"lat\" : 47.934780, \"lng\" : -1"
            + "22.20710},\"html_instructions\" : \"Slight \\u003cb\\u003eleft\\u003c"
            + "/b\\u003e to stay on \\u003cb\\u003eInterurban Trail\\u003c/b\\u003e"
            + "\",\"polyline\" : { \"points\" : \"s}ocHfl|hVMMC?C@OFm@NI?I?m@Mi@U_@IS"
            + "CO@]JQ@y@I}AWuA]o@SyAo@yA{@gAeAq@q@OMqJaLDM?EAGEKCECCOMYWAE\"},\"start"
            + "_location\" : { \"lat\" : 47.92810, \"lng\" : -122.21140},\"travel_mod"
            + "e\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \"144 ft\", \"valu"
            + "e\" : 44},\"duration\" : { \"text\" : \"1 min\", \"value\" : 8},\"end_"
            + "location\" : { \"lat\" : 47.935160, \"lng\" : -122.207020},\"html_instr"
            + "uctions\" : \"Slight \\u003cb\\u003eleft\\u003c/b\\u003e to stay on \\u"
            + "003cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"point"
            + "s\" : \"kgqcHjq{hVMAO?S?MAEAEI\"},\"start_location\" : { \"lat\" : 47.9"
            + "34780, \"lng\" : -122.20710},\"travel_mode\" : \"BICYCLING\" }, {\"dista"
            + "nce\" : { \"text\" : \"495 ft\", \"value\" : 151},\"duration\" : { \""
            + "text\" : \"1 min\", \"value\" : 19},\"end_location\" : { \"lat\" : 47."
            + "936170, \"lng\" : -122.205710},\"html_instructions\" : \"Slight \\u003"
            + "cb\\u003eright\\u003c/b\\u003e to stay on \\u003cb\\u003eInterurban T"
            + "rail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"wiqcHzp{hVO]KS"
            + "}BoCe@i@CAAAACAC?M\"},\"start_location\" : { \"lat\" : 47.935160, \"l"
            + "ng\" : -122.207020},\"travel_mode\" : \"BICYCLING\" }, {\"distance\""
            + " : { \"text\" : \"0.8 mi\", \"value\" : 1256},\"duration\" : { \""
            + "text\" : \"3 mins\", \"value\" : 207},\"end_location\" : { \"lat\" : "
            + "47.946370, \"lng\" : -122.200860},\"html_instructions\" : \"Turn \\u00"
            + "3cb\\u003eleft\\u003c/b\\u003e onto \\u003cb\\u003eCommercial Ave/Inte"
            + "rurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\" : \"apqcHth"
            + "{hVC?OASGKGMQe@i@kAoAcDuDkDsDmD_EiDmDk@]e@YSKgAg@eB_@eAKiAG[A]?Q?UD_@D]"
            + "@kAEoBIMCeAE{@?iAFo@Jc@He@Ng@R_@V\"},\"start_location\" : { \"lat\" : "
            + "47.936170, \"lng\" : -122.205710},\"travel_mode\" : \"BICYCLING\" }, "
            + "{\"distance\" : { \"text\" : \"0.1 mi\", \"value\" : 231},\"duratio"
            + "n\" : { \"text\" : \"1 min\", \"value\" : 51},\"end_location\" : { "
            + "\"lat\" : 47.948160, \"lng\" : -122.201630},\"html_instructions\""
            + " : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u00"
            + "3eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"points\""
            + " : \"yoscHjjzhVCMC?c@RgBnAa@^[^YVe@TQLG@E?CCECIKGIEIGGAAGG\"},\""
            + "start_location\" : { \"lat\" : 47.946370, \"lng\" : -122.200860"
            + "},\"travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" :"
            + " \"0.2 mi\", \"value\" : 277},\"duration\" : { \"text\" : \"1 min\""
            + ", \"value\" : 38},\"end_location\" : { \"lat\" : 47.949770, \"lng\""
            + " : -122.204270},\"html_instructions\" : \"Turn \\u003cb\\u003eleft\\u"
            + "003c/b\\u003e to stay on \\u003cb\\u003eInterurban Trail\\u003c/b\\u0"
            + "03e\",\"polyline\" : { \"points\" : \"_{scHdozhVQRo@z@wApBa@d@GJG"
            + "NERAT?n@?PCPSd@uAfB\"},\"start_location\" : { \"lat\" : 47.948160"
            + ", \"lng\" : -122.201630},\"travel_mode\" : \"BICYCLING\" }, {\"dist"
            + "ance\" : { \"text\" : \"0.1 mi\", \"value\" : 175},\"duration\" : {"
            + " \"text\" : \"1 min\", \"value\" : 51},\"end_location\" : { \"lat"
            + "\" : 47.95110, \"lng\" : -122.205510},\"html_instructions\" : \"C"
            + "ontinue onto \\u003cb\\u003eAlta Dr\\u003c/b\\u003e\",\"polyline"
            + "\" : { \"points\" : \"aetcHt_{hVaAjAYXWVu@h@_Al@]\\\\AB\"},\"sta"
            + "rt_location\" : { \"lat\" : 47.949770, \"lng\" : -122.204270},\""
            + "travel_mode\" : \"BICYCLING\" }, {\"distance\" : { \"text\" : \""
            + "0.6 mi\", \"value\" : 935},\"duration\" : { \"text\" : \"3 mins"
            + "\", \"value\" : 151},\"end_location\" : { \"lat\" : 47.959410000"
            + "00001, \"lng\" : -122.207220},\"html_instructions\" : \"Slight \\u0"
            + "03cb\\u003eright\\u003c/b\\u003e onto \\u003cb\\u003eInterurban Tr"
            + "ail\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eR"
            + "estricted usage road\\u003c/div\\u003e\",\"polyline\" : { \"points\""
            + " : \"kmtcHlg{hVUCCAC?C@_@FaARGBE@aCTG?I@_Ep@yARsKz@gCPiBRk@DoB\\\\w"
            + "Bb@GBGBWLGBk@Jo@HW?\"},\"start_location\" : { \"lat\" : 47.95110, "
            + "\"lng\" : -122.205510},\"travel_mode\" : \"BICYCLING\" }, {\"dista"
            + "nce\" : { \"text\" : \"0.3 mi\", \"value\" : 467},\"duration\" : {"
            + " \"text\" : \"2 mins\", \"value\" : 124},\"end_location\" : { \"la"
            + "t\" : 47.96331000000001, \"lng\" : -122.20790},\"html_instructions"
            + "\" : \"Turn \\u003cb\\u003eleft\\u003c/b\\u003e to stay on \\u003"
            + "cb\\u003eInterurban Trail\\u003c/b\\u003e\",\"polyline\" : { \"po"
            + "ints\" : \"iavcHbr{hVG@C@?B?J@f@?LCFC@E@gDDgA@OAC?C@A@C?GCOCI?SBO"
            + "?I@S@kADw@BEA]E[Eu@D{ABE@E?E@A@C@SX\"},\"start_location\" : { \"l"
            + "at\" : 47.95941000000001, \"lng\" : -122.207220},\"travel_mode\" "
            + ": \"BICYCLING\" }, {\"distance\" : { \"text\" : \"1.1 mi\", \"val"
            + "ue\" : 1772},\"duration\" : { \"text\" : \"6 mins\", \"value\" :"
            + " 331},\"end_location\" : { \"lat\" : 47.979240, \"lng\" : -122.2"
            + "0860},\"html_instructions\" : \"Slight \\u003cb\\u003eright\\u00"
            + "3c/b\\u003e onto \\u003cb\\u003eColby Ave\\u003c/b\\u003e\",\"po"
            + "lyline\" : { \"points\" : \"uyvcHjv{hVmGNkGHcGLgGLgGDcGJkGLgGHaG"
            + "LmGHgGNsGB\"},\"start_location\" : { \"lat\" : 47.96331000000001"
            + ", \"lng\" : -122.20790},\"travel_mode\" : \"BICYCLING\" }, {\"di"
            + "stance\" : { \"text\" : \"0.3 mi\", \"value\" : 487},\"duration\""
            + " : { \"text\" : \"1 min\", \"value\" : 74},\"end_location\" : { "
            + "\"lat\" : 47.97922000000001, \"lng\" : -122.202080},\"html_instr"
            + "uctions\" : \"Turn \\u003cb\\u003eright\\u003c/b\\u003e onto \\u"
            + "003cb\\u003eHewitt Ave\\u003c/b\\u003e\\u003cdiv style=\\\"font-"
            + "size:0.9em\\\"\\u003eDestination will be on the right\\u003c/div"
            + "\\u003e\",\"polyline\" : { \"points\" : \"g}ycHvz{hV?uGDwG?{GFuG"
            + "?_AI]?yA\"},\"start_location\" : { \"lat\" : 47.979240, \"lng\" "
            + ": -122.20860},\"travel_mode\" : \"BICYCLING\" }],\"via_waypoint\""
            + " : [ {\"location\" : { \"lat\" : 47.70634310, \"lng\" : -122.2754"
            + "8620},\"step_index\" : 7,\"step_interpolation\" : 0.4439827775569"
            + "065 }] }],\"overview_polyline\" : { \"points\" : \"eq|aHvtriV?h@q"
            + "C?aHCiQI}TKqHGwCA@qE@_G@kJ?sBDoPDeUA{n@F_U?sb@?kY?eIAaC?kCkEB_DBi"
            + "JJaNL_WVc]\\\\e[YuLCw@A?y@?iBJu`@ByM@gKhA?~@?JoBJaDHi@|@_ATg@k@q@"
            + "e@u@_AsDgAkFaAoCoAuB{@y@kA{@mAe@yAU}ABkD`AiLnD{HdCkF|A{@FeDOmBD}S"
            + "hGuBXiH`@yVlGwHjByCfAuFfH_Ap@cCj@eGp@gBW{LqC_AE_El@{LvFuBf@eB?sFo"
            + "@cBZmAp@qAzAgB~CaCrCcAj@_BXeCl@qI~E_Cl@wBGmBs@sJiGwAYwBGmIAiGs@mK"
            + "sAgHsCuOwGeBkA{AmBy@iBc@g@Ko@gByGgDkK[i@[eB}CqIeFmK{AqBgDgE}@cC_@"
            + "uBoAgN}@gJ?uATqNs@eYg@cRDaHIkBf@mQLuBbCkXh@aIQ?eSLcEMgBc@iAo@uEmD"
            + "aJ\\\\aDTyEP{@I{DiA\\\\{Cd@yIpCoLj@oC?kQ?aC_AAqEGyUWwPW{`@ETem@Dm"
            + "[@uHmCnBo@`@oAb@_BVeDU_Q{CoFkAoEAyBUg@UqG_GmCoCqFyE_HqDkHsDkFwCo"
            + "M}GyJ}E{LcHeEaCkAc@cFeC}Cw@}IMcGAwGAUJgCEqPMyLCwr@IeE|@{B|@yD~BgB"
            + "r@sARyAHaIWiFWiDb@_ErB}MnImFbEuGnJw@|@yDdCwDz@m_@rBgBLiFnAcKxCcA"
            + "\\\\k@@aFhBuBTcLTuFPmIp@_YrB_CBoJmAeR}BuBGmGT{GNoCO_Ba@yCcBoH}E}"
            + "CsC_F}FcKeMk@yAiAgFsB{PU}@g@_AWGcPOif@a@qMG_ASkA_@_ByAyAiAODs@s@"
            + "m@s@gAaBeDyFgDeDcBo@}AFsBfAU`@K^U|DI~HOjBa@x@s@n@sDRQ@?Z\\\\zF`B"
            + "r_@XzHDzIApQChTgI@qTRs[ReZLgNN{IBsRPoAIQq@E_AkDBoOFw@@[PSTUs@g@{"
            + "AcA}CnAmPTqH?qIB}AR_A@oBM{@Uc@aGoC_KsEaDw@sGg@m@i@eAXkBc@s@Mm@Lk"
            + "AGsDu@iCcAaDaCaA_AqJaLDMAMIQo@o@_ACg@}@iD}DGUc@IYYaMcNwImJqAw@{A"
            + "s@kDk@uCIu@JiBC_GSyBRiAXgAj@GMkCbB}@~@yA|@YSW]YJgClDw@tAEhBiBlC{"
            + "AdBkDlC_@AmB`@yCXyGdA{OlA}JzAo@X{BVAx@MXcGDoA?aDLuBGmBFEBSXmGNoO"
            + "VoORy_@p@uOXsGB?uGDsPFuIIwB\"},\"summary\" : \"Bothell Everett H"
            + "wy\",\"warnings\" : [ \"Bicycling directions are in beta. Use ca"
            + "ution \u2013 This route may contain streets that aren\'t suited "
            + "for bicycling.\"],\"waypoint_order\" : [] }],\"status\" : \"OK\" }";

    /**
     * Query that I'm using that the stub will return null with. This is
     * technically a valid query but I need something to get the stub to return
     * null.
     */
    private final String case3URLQuery = "http://maps.googleapis.com/maps/api/directions/json?"
            + "origin=3801+Brooklyn+Ave+NE%2CSeattle%2CWA&destination=1320+S+Maple+Grove+Road"
            + "%2C+Boise%2C+ID&sensor=true&mode=bicycling&alternatives=true&language=en";

    /**
     * The JSON response that the case3URLQuery maps to. We are simulating a
     * null response from the GoogleAPIs with this one. By checking for null in
     * our doQuery method we know to throw an IOException(), meaning we could
     * not connect to Google.
     */
    private final String case3JSONResponseConnectionFailedThrowIOException = null;

    /**
     * A query that the origin and destination fields are made up. This will
     * cause the Google APIs to return a route with zero results.
     */
    private final String case4URLQuery = "http://maps.googleapis.com/maps/api/directions/"
            + "json?origin=pig&destination=bacon&sensor=true&mode=bicycling&alternatives"
            + "=true&language=en";

    /**
     * The JSON response that the case4URLQuery maps to.
     */
    private final String case4JSONResponseGoogleReturnsNoResults = "{\"routes\":[],\"status\":\"ZERO_RESULTS\"}";

    /**
     * Query that I'm using that the stub will return "Request Denied" status.
     * This is technically a valid query (even though it would technically
     * return ZERO_RESULTS) but I need something to get the stub to return
     * "Request Denied" with. If I chose an invalid query the validate
     * parameters method would prevent it from getting any farther in the code.
     */
    private final String case5URLQuery = "http://maps.googleapis.com/maps/api/directions/"
            + "json?origin=cow&destination=steak&sensor=true&mode=bicycling&alternatives="
            + "true&language=en";

    /**
     * The JSON response that the case5URLQuery maps to.
     */
    private final String case5JSONResponseGoogleDeniesRequest = "{\"routes\":[],\"status\" : \"REQUEST_DENIED\"}";

    /**
     * Constructor that loads all of the query-response mappings into the
     * hashMap.
     */
    public StubGoogleAPIWrapper() {
        queryMap.put(case1URLQuery, case1JSONResponseStandardResponse);
        queryMap.put(case2URLQuery, case2JSONResponseStressTest);
        queryMap.put(case3URLQuery, case3JSONResponseConnectionFailedThrowIOException);
        queryMap.put(case4URLQuery, case4JSONResponseGoogleReturnsNoResults);
        queryMap.put(case5URLQuery, case5JSONResponseGoogleDeniesRequest);
    }

    /**
     * (non-Javadoc) @see
     * com.HuskySoft.metrobike.backend.APIQuery#doQuery(java.lang.String).
     * 
     * @param theURL
     *            The theURL with the parameters to make the request to.
     * 
     * @throws IOException
     *             If the connection to the Google Maps APIs is not reached.
     * 
     * @return The JSON response.
     */
    public final String doQuery(final String theURL) throws IOException {
        //System.out.println(TAG + "doQuery()->theURL: " + theURL);
        if (theURL == null) {
            throw new IllegalArgumentException("theURL parameter was null.");
        } else if (!queryMap.containsKey(theURL)) {
            throw new IllegalArgumentException("theURL: " + theURL
                    + " Did not exist in the queryMap.");
        } else {
            String jsonResponse = queryMap.get(theURL);
            if (jsonResponse == null) {
                throw new IOException("Simulating the failure to connect to the Google Map APIs");
            } else {
                return jsonResponse;
            }
        }
    }
}