package com.HuskySoft.metrobike.algorithm;

/**
 * Holds various standard error messages that may be generated by Algorithms.
 * These messages are designed to be passed back to the user.
 * 
 * @author dutchscout
 * 
 */
enum AlgorithmError {

    /**
     * Attempted to ask an algorithm for a travel mode that isn't supported (ex:
     * walking).
     */
    UNSUPPORTED_TRAVEL_MODE_ERROR("Requested travel mode not supported."),

    /**
     * The default charset is not supported.
     */
    UNSUPPORTED_CHARSET("Internal error: default charset not supported."),

    /**
     * Couldn't parse the server's response.
     */
    PARSING_ERROR("Got a bad response from the server."),

    /**
     * Any kind of connection error.
     */
    CONNECTION_ERROR("Having trouble connecting to the server.  Please try again later"),

    /**
     * No results found. Probably a problem with location or travel time.
     */
    NO_RESULTS_FOUND(
            "Found no results.  Please check to be sure your addresses and travel options!");

    /**
     * The human-readable message to store.
     */
    private String message;

    /**
     * Private constructor (to prevent re-construction).
     * 
     * @param enumMessage
     *            the message associated with this enum value
     */
    private AlgorithmError(final String enumMessage) {
        message = enumMessage;
    }

    /**
     * Returns a human-readable error message for this enum value.
     * 
     * @return a human-readable error message for this enum value
     */
    public String getMessage() {
        return message;
    }
}