package com.HuskySoft.metrobike.algorithm;

/**
 * Holds various standard error messages that may be generated by
 * Algorithms.
 * 
 * @author dutchscout
 * 
 */
enum AlgorithmError {

    /**
     * Attempted to ask an algorithm for a travel mode that isn't supported
     * (ex: walking).
     */
    UNSUPPORTED_TRAVEL_MODE_ERROR("Travel mode not supported"),
    
    /**
     * The default charset is not supported.
     */
    UNSUPPORTED_CHARSET("Internal error: default charset not supported");

    /**
     * The human-readable message to store.
     */
    private String message;

    /**
     * Private constructor (to prevent re-construction).
     * 
     * @param enumMessage
     *            the message associated with this enum value
     */
    private AlgorithmError(final String enumMessage) {
        message = enumMessage;
    }

    /**
     * Returns a human-readable error message for this enum value.
     * 
     * @return a human-readable error message for this enum value
     */
    public String getMessage() {
        return message;
    }
}